// Command specbundle assembles api/openapi.yaml from the fragment files
// in api/spec. The contract is authored as one file per API domain plus
// _root.yaml (openapi, info, servers, tags, security); every consumer of
// the contract (oapi-codegen, the Dart generator, spectral, oasdiff, CI)
// keeps reading the single bundled file, which stays committed.
//
// Bundling is textual: each fragment's section bodies are moved into the
// bundle verbatim, so hand-written formatting, comments, and deliberate
// quoting (YAML 1.1 booleans like "off") survive byte for byte. Safety
// comes from a semantic self-check instead of from re-encoding: the
// assembled bundle is parsed and deep-compared against the merged
// fragment documents, and any mismatch is a hard error before the output
// is written. Duplicate paths or component names across fragments are
// errors, as are top-level keys outside the fragment contract.
//
// Run as: go run ./cmd/specbundle -src ../api/spec -out ../api/openapi.yaml
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const rootName = "_root.yaml"

// kindOrder fixes the emission order of component kinds in the bundle.
// The first four match the monolith's historical layout; the rest are
// the remaining OpenAPI 3.0 kinds, accepted so a fragment can introduce
// one without touching this tool. Unknown names still error (typo guard).
var kindOrder = []string{
	"securitySchemes", "parameters", "responses", "schemas",
	"requestBodies", "headers", "examples", "links", "callbacks",
}

var rootKeys = map[string]bool{
	"openapi": true, "info": true, "servers": true, "tags": true, "security": true,
}

const banner = "# Code generated by specbundle from api/spec/*.yaml; DO NOT EDIT.\n" +
	"# Edit the fragment files in api/spec/ and run `make generate`.\n"

func main() {
	src := flag.String("src", "api/spec", "directory of spec fragment files")
	out := flag.String("out", "api/openapi.yaml", "bundled spec to write")
	flag.Parse()
	if err := bundle(*src, *out); err != nil {
		fmt.Fprintf(os.Stderr, "specbundle: %v\n", err)
		os.Exit(1)
	}
}

// fragment is one domain file: its decoded document (for validation and
// the self-check) and the verbatim text of each section body.
type fragment struct {
	name  string
	doc   map[string]any
	paths []string            // body lines under paths:, nil if absent
	kinds map[string][]string // component kind -> body lines
}

func bundle(src, out string) error {
	names, err := fragmentNames(src)
	if err != nil {
		return err
	}

	rootText, rootDoc, err := loadRoot(filepath.Join(src, rootName))
	if err != nil {
		return err
	}

	var frags []*fragment
	for _, name := range names {
		f, err := loadFragment(filepath.Join(src, name))
		if err != nil {
			return err
		}
		frags = append(frags, f)
	}

	merged, err := mergeDocs(rootDoc, frags)
	if err != nil {
		return err
	}

	text := assemble(rootText, frags)

	// Self-check: the assembled text must mean exactly what the merged
	// fragment documents mean. This is what makes textual carving safe.
	var got any
	if err := yaml.Unmarshal([]byte(text), &got); err != nil {
		return fmt.Errorf("internal: assembled bundle is not valid YAML: %w", err)
	}
	if !reflect.DeepEqual(got, any(merged)) {
		return fmt.Errorf("internal: assembled bundle does not match fragment semantics; not writing %s", out)
	}

	return writeIfChanged(out, []byte(text))
}

// fragmentNames lists the non-root fragment files in bundle order.
// Anything unexpected in the directory is an error, never a silent
// skip: a fragment saved as .yml or misplaced in a subdirectory must
// not quietly vanish from the bundle. Hidden files (editor swap
// files, .DS_Store) are the one tolerated class.
func fragmentNames(src string) ([]string, error) {
	entries, err := os.ReadDir(src)
	if err != nil {
		return nil, err
	}
	var names []string
	rootSeen := false
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), ".") {
			continue
		}
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".yaml") {
			return nil, fmt.Errorf("%s: unexpected entry %q (fragments are flat .yaml files)", src, e.Name())
		}
		if e.Name() == rootName {
			rootSeen = true
			continue
		}
		names = append(names, e.Name())
	}
	if !rootSeen {
		return nil, fmt.Errorf("%s: missing %s", src, rootName)
	}
	if len(names) == 0 {
		return nil, fmt.Errorf("%s: no fragment files besides %s", src, rootName)
	}
	sort.Strings(names)
	return names, nil
}

// loadRoot reads the preamble fragment. Its body (from the first key
// onward) is emitted verbatim; a leading comment block is treated as a
// file header and dropped.
func loadRoot(path string) (body []string, doc map[string]any, err error) {
	lines, doc, err := readFragmentFile(path)
	if err != nil {
		return nil, nil, err
	}
	for k := range doc {
		if !rootKeys[k] {
			return nil, nil, fmt.Errorf("%s: key %q does not belong in the root fragment", path, k)
		}
	}
	for _, k := range []string{"openapi", "info"} {
		if _, ok := doc[k]; !ok {
			return nil, nil, fmt.Errorf("%s: missing required key %q", path, k)
		}
	}
	return lines, doc, nil
}

// loadFragment reads one domain fragment and carves its section bodies.
func loadFragment(path string) (*fragment, error) {
	lines, doc, err := readFragmentFile(path)
	if err != nil {
		return nil, err
	}
	f := &fragment{name: filepath.Base(path), doc: doc, kinds: map[string][]string{}}
	for k := range doc {
		if k != "paths" && k != "components" {
			return nil, fmt.Errorf("%s: key %q does not belong in a domain fragment (only paths, components)", path, k)
		}
	}

	pre, secs := carve(lines, 0)
	if l, ok := firstContent(pre); ok {
		return nil, fmt.Errorf("%s: unexpected content before the first top-level key: %q", path, l)
	}
	for _, sec := range secs {
		switch sec.key {
		case "paths":
			if len(sec.body) == 0 {
				return nil, fmt.Errorf("%s: empty paths section", path)
			}
			f.paths = sec.body
		case "components":
			kpre, kinds := carve(sec.body, 2)
			if l, ok := firstContent(kpre); ok {
				if strings.HasPrefix(strings.TrimSpace(l), "#") {
					return nil, fmt.Errorf("%s: comment between components: and the first kind key (%q); move it into the file header or below the kind line", path, l)
				}
				return nil, fmt.Errorf("%s: components content not at the expected indent (%q): kind keys must be indented exactly two spaces", path, l)
			}
			for _, kind := range kinds {
				if !kindKnown(kind.key) {
					return nil, fmt.Errorf("%s: unknown component kind %q", path, kind.key)
				}
				if len(kind.body) == 0 {
					return nil, fmt.Errorf("%s: empty components.%s section", path, kind.key)
				}
				f.kinds[kind.key] = kind.body
			}
		default:
			return nil, fmt.Errorf("%s: unexpected top-level key %q", path, sec.key)
		}
	}

	// Cross-check the carve against the parsed document, so an authoring
	// mistake the carver cannot see (a section inline, a kind indented
	// four spaces) fails here with the file named, not later in the
	// bundle-wide self-check.
	if _, ok := f.doc["paths"]; ok && f.paths == nil {
		return nil, fmt.Errorf("%s: paths exists in the document but was not carved (inline or unusually indented?)", path)
	}
	if c, ok := f.doc["components"]; ok {
		if cm, ok := c.(map[string]any); ok {
			for kind := range cm {
				if _, carved := f.kinds[kind]; !carved {
					return nil, fmt.Errorf("%s: components.%s exists in the document but was not carved: kind keys must be indented exactly two spaces", path, kind)
				}
			}
		}
	}
	return f, nil
}

// firstContent reports the first non-blank line, if any.
func firstContent(lines []string) (string, bool) {
	for _, l := range lines {
		if strings.TrimSpace(l) != "" {
			return l, true
		}
	}
	return "", false
}

// readFragmentFile splits a fragment into its body lines (leading comment
// header dropped, trailing blank lines trimmed) and its decoded document.
func readFragmentFile(path string) ([]string, map[string]any, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, err
	}
	// Tolerate CRLF checkouts (Windows autocrlf); the bundle is always LF.
	text := strings.ReplaceAll(string(raw), "\r\n", "\n")
	var doc map[string]any
	if err := yaml.Unmarshal([]byte(text), &doc); err != nil {
		return nil, nil, fmt.Errorf("%s: %w", path, err)
	}
	if doc == nil {
		return nil, nil, fmt.Errorf("%s: empty document", path)
	}
	lines := strings.Split(strings.TrimRight(text, "\n"), "\n")
	for len(lines) > 0 {
		t := strings.TrimSpace(lines[0])
		if t == "" || strings.HasPrefix(t, "#") {
			lines = lines[1:]
			continue
		}
		break
	}
	return trimBlank(lines), doc, nil
}

type section struct {
	key  string
	body []string
}

// carve splits lines into sections keyed at the given indent. A section
// key line must be "<indent><key>:" (a trailing comment is tolerated);
// everything up to the next key at that indent is its body, moved
// verbatim. Lines before the first key are returned as prefix so the
// caller can refuse non-blank ones instead of dropping them.
func carve(lines []string, indent int) (prefix []string, secs []section) {
	pad := strings.Repeat(" ", indent)
	isKey := func(l string) bool {
		rest, ok := strings.CutPrefix(l, pad)
		return ok && len(rest) > 0 && rest[0] != ' ' && rest[0] != '#'
	}
	for i := 0; i < len(lines); i++ {
		if !isKey(lines[i]) {
			if len(secs) == 0 {
				prefix = append(prefix, lines[i])
			}
			continue
		}
		key := sectionKey(strings.TrimPrefix(lines[i], pad))
		end := i + 1
		for end < len(lines) && !isKey(lines[end]) {
			end++
		}
		secs = append(secs, section{key: key, body: trimBlank(lines[i+1 : end])})
		i = end - 1
	}
	return prefix, secs
}

// sectionKey extracts the key from a section line, tolerating a trailing
// comment or whitespace ("schemas:  # admin DTOs" -> "schemas"). Such a
// comment stays in the fragment only: the bundle emits canonical section
// headers, and bodies are carved below the key line.
func sectionKey(line string) string {
	for _, marker := range []string{" #", "\t#"} {
		if i := strings.Index(line, marker); i >= 0 {
			line = line[:i]
		}
	}
	return strings.TrimSuffix(strings.TrimRight(line, " \t"), ":")
}

func trimBlank(lines []string) []string {
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}
	return lines
}

func kindKnown(k string) bool {
	for _, known := range kindOrder {
		if k == known {
			return true
		}
	}
	return false
}

// mergeDocs unions the decoded fragment documents under the root, and is
// where cross-fragment duplicates are caught.
func mergeDocs(root map[string]any, frags []*fragment) (map[string]any, error) {
	merged := map[string]any{}
	for k, v := range root {
		merged[k] = v
	}
	paths := map[string]any{}
	pathOwner := map[string]string{}
	comps := map[string]any{}
	compOwner := map[string]string{}

	for _, f := range frags {
		if p, ok := f.doc["paths"]; ok {
			pm, ok := p.(map[string]any)
			if !ok {
				return nil, fmt.Errorf("%s: paths is not a mapping", f.name)
			}
			for k, v := range pm {
				if prev, dup := pathOwner[k]; dup {
					return nil, fmt.Errorf("path %s defined in both %s and %s", k, prev, f.name)
				}
				pathOwner[k] = f.name
				paths[k] = v
			}
		}
		if c, ok := f.doc["components"]; ok {
			cm, ok := c.(map[string]any)
			if !ok {
				return nil, fmt.Errorf("%s: components is not a mapping", f.name)
			}
			for kind, names := range cm {
				nm, ok := names.(map[string]any)
				if !ok {
					return nil, fmt.Errorf("%s: components.%s is not a mapping", f.name, kind)
				}
				dst, ok := comps[kind].(map[string]any)
				if !ok {
					dst = map[string]any{}
					comps[kind] = dst
				}
				for k, v := range nm {
					id := kind + "/" + k
					if prev, dup := compOwner[id]; dup {
						return nil, fmt.Errorf("components.%s defined in both %s and %s", id, prev, f.name)
					}
					compOwner[id] = f.name
					dst[k] = v
				}
			}
		}
	}
	if len(paths) > 0 {
		merged["paths"] = paths
	}
	if len(comps) > 0 {
		merged["components"] = comps
	}
	return merged, nil
}

// assemble builds the bundle text: banner, root preamble, then the paths
// and component sections concatenated in fragment order with one blank
// line between bodies.
func assemble(rootBody []string, frags []*fragment) string {
	var b strings.Builder
	b.WriteString(banner)
	writeLines(&b, rootBody)

	var pathBodies [][]string
	kindBodies := map[string][][]string{}
	for _, f := range frags {
		if f.paths != nil {
			pathBodies = append(pathBodies, f.paths)
		}
		for _, kind := range kindOrder {
			if body, ok := f.kinds[kind]; ok {
				kindBodies[kind] = append(kindBodies[kind], body)
			}
		}
	}

	if len(pathBodies) > 0 {
		b.WriteString("\npaths:\n")
		writeBodies(&b, pathBodies)
	}
	if len(kindBodies) > 0 {
		b.WriteString("\ncomponents:\n")
		for _, kind := range kindOrder {
			if bodies, ok := kindBodies[kind]; ok {
				b.WriteString("  " + kind + ":\n")
				writeBodies(&b, bodies)
			}
		}
	}
	return b.String()
}

func writeBodies(b *strings.Builder, bodies [][]string) {
	for i, body := range bodies {
		if i > 0 {
			b.WriteString("\n")
		}
		writeLines(b, body)
	}
}

func writeLines(b *strings.Builder, lines []string) {
	for _, l := range lines {
		b.WriteString(l)
		b.WriteString("\n")
	}
}

// writeIfChanged replaces out atomically (temp in target dir, fsync,
// rename) and leaves an up-to-date file untouched. The temp file's
// 0600 creation mode must not leak through the rename: the bundle
// keeps the existing file's permissions, or 0644 for a fresh one.
func writeIfChanged(out string, data []byte) error {
	if old, err := os.ReadFile(out); err == nil && bytes.Equal(old, data) {
		return nil
	}
	mode := os.FileMode(0o644)
	if st, err := os.Stat(out); err == nil {
		mode = st.Mode().Perm()
	}
	tmp, err := os.CreateTemp(filepath.Dir(out), ".specbundle-*.yaml")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), out)
}
