package main

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"gopkg.in/yaml.v3"
)

const testRoot = `openapi: 3.0.3
info:
  title: T
  version: "1.0"
tags:
  - name: a
`

func writeSpec(t *testing.T, files map[string]string) (src, out string) {
	t.Helper()
	dir := t.TempDir()
	src = filepath.Join(dir, "spec")
	if err := os.Mkdir(src, 0o755); err != nil {
		t.Fatal(err)
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(src, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return src, filepath.Join(dir, "openapi.yaml")
}

func TestBundleMergesVerbatim(t *testing.T) {
	src, out := writeSpec(t, map[string]string{
		"_root.yaml": testRoot,
		"a.yaml": `# file header, dropped from the bundle
  # indented continuation, also dropped
paths:
  /a:
    get:
      operationId: getA
      responses:
        "200":
          description: ok

components:
  schemas:
    A:
      type: string
      # deliberate YAML 1.1 quoting survives verbatim
      enum: ["off", "on"]
`,
		"b.yaml": `paths:
  /b:
    get:
      operationId: getB
      responses:
        "200":
          description: ok

components:
  parameters:
    P:
      name: p
      in: query
      schema:
        type: string
  requestBodies:
    RB:
      content:
        application/json:
          schema:
            type: object
  schemas:  # trailing comment on the kind line
    B:
      type: object
`,
	})
	if err := bundle(src, out); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	text := string(raw)

	for _, want := range []string{
		"# Code generated by specbundle",
		"\npaths:\n",
		"\ncomponents:\n",
		`enum: ["off", "on"]`,
		"# deliberate YAML 1.1 quoting survives verbatim",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("bundle missing %q", want)
		}
	}
	for _, header := range []string{"file header", "indented continuation"} {
		if strings.Contains(text, header) {
			t.Errorf("fragment file header %q leaked into the bundle", header)
		}
	}

	var doc map[string]any
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	paths := doc["paths"].(map[string]any)
	if _, ok := paths["/a"]; !ok {
		t.Error("missing /a")
	}
	if _, ok := paths["/b"]; !ok {
		t.Error("missing /b")
	}
	comps := doc["components"].(map[string]any)
	if _, ok := comps["schemas"].(map[string]any)["B"]; !ok {
		t.Error("missing schema B")
	}
	if _, ok := comps["parameters"].(map[string]any)["P"]; !ok {
		t.Error("missing parameter P")
	}
	if _, ok := comps["requestBodies"].(map[string]any)["RB"]; !ok {
		t.Error("missing request body RB")
	}

	// A fresh bundle must not inherit the temp file's 0600 mode. Asked
	// only off Windows, which has no POSIX bits to report.
	if runtime.GOOS != "windows" {
		st, err := os.Stat(out)
		if err != nil {
			t.Fatal(err)
		}
		if st.Mode().Perm() != 0o644 {
			t.Errorf("bundle mode = %o, want 644", st.Mode().Perm())
		}
	}

	// Second run must be a no-op on identical input. Anchor the mtime in
	// the past so a rewrite is detectable on any timestamp granularity.
	past := time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)
	if err := os.Chtimes(out, past, past); err != nil {
		t.Fatal(err)
	}
	if err := bundle(src, out); err != nil {
		t.Fatal(err)
	}
	st, err := os.Stat(out)
	if err != nil {
		t.Fatal(err)
	}
	if !st.ModTime().Equal(past) {
		t.Error("unchanged bundle was rewritten")
	}
}

func TestBundleNormalizesCRLF(t *testing.T) {
	src, out := writeSpec(t, map[string]string{
		"_root.yaml": testRoot,
		"a.yaml": strings.ReplaceAll(`paths:
  /a:
    get:
      operationId: getA
      responses:
        "200":
          description: ok
`, "\n", "\r\n"),
	})
	if err := bundle(src, out); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(raw), "\r") {
		t.Error("CRLF fragment leaked carriage returns into the bundle")
	}
	var doc map[string]any
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	if _, ok := doc["paths"].(map[string]any)["/a"]; !ok {
		t.Error("missing /a from CRLF fragment")
	}
}

func TestBundleIgnoresHiddenFiles(t *testing.T) {
	src, out := writeSpec(t, map[string]string{
		"_root.yaml":   testRoot,
		"a.yaml":       "components:\n  schemas:\n    S:\n      type: string\n",
		".a.yaml.swp":  "not yaml at all {{{",
		".DS_Store":    "junk",
		".hidden.yaml": "junk: [",
	})
	if err := bundle(src, out); err != nil {
		t.Fatal(err)
	}
}

func TestBundleRejects(t *testing.T) {
	frag := func(body string) map[string]string {
		return map[string]string{"_root.yaml": testRoot, "x.yaml": body}
	}
	dup := `paths:
  /a:
    get:
      operationId: getA
      responses:
        "200":
          description: ok
`
	cases := []struct {
		name  string
		files map[string]string
		want  string
	}{
		{"missing root", map[string]string{"a.yaml": dup}, "missing _root.yaml"},
		{"duplicate path", map[string]string{
			"_root.yaml": testRoot, "a.yaml": dup, "b.yaml": dup,
		}, "defined in both"},
		{"duplicate schema", map[string]string{
			"_root.yaml": testRoot,
			"a.yaml":     "components:\n  schemas:\n    S:\n      type: string\n",
			"b.yaml":     "components:\n  schemas:\n    S:\n      type: object\n",
		}, "defined in both"},
		{"unknown top-level key", frag("servers:\n  - url: /x\n"), "does not belong in a domain fragment"},
		{"unknown component kind", frag("components:\n  pathItems:\n    P:\n      description: 3.1-only\n"), "unknown component kind"},
		// A repeated section is a duplicate YAML mapping key; the parser
		// rejects it before carving, so no silent overwrite is possible.
		{"duplicate section in one fragment", frag(dup + dup), "already defined"},
		{"stray .yml fragment", map[string]string{
			"_root.yaml": testRoot, "a.yaml": dup, "b.yml": dup,
		}, "unexpected entry"},
		{"comment before first kind", frag("components:\n  # stranded comment\n  schemas:\n    S:\n      type: string\n"), "comment between components:"},
		{"kind indented four spaces", frag("components:\n    schemas:\n      S:\n        type: string\n"), "indented exactly two spaces"},
		{"root with paths", map[string]string{
			"_root.yaml": testRoot + dup,
			"a.yaml":     "components:\n  schemas:\n    S:\n      type: string\n",
		}, "does not belong in the root fragment"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			src, out := writeSpec(t, tc.files)
			err := bundle(src, out)
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("got %v, want error containing %q", err, tc.want)
			}
			if _, statErr := os.Stat(out); statErr == nil {
				t.Error("output written despite error")
			}
		})
	}

	t.Run("subdirectory in spec dir", func(t *testing.T) {
		src, out := writeSpec(t, map[string]string{"_root.yaml": testRoot, "a.yaml": dup})
		if err := os.Mkdir(filepath.Join(src, "nested"), 0o755); err != nil {
			t.Fatal(err)
		}
		err := bundle(src, out)
		if err == nil || !strings.Contains(err.Error(), "unexpected entry") {
			t.Fatalf("got %v, want error containing %q", err, "unexpected entry")
		}
	})
}
