.PHONY: generate spec-bundle gen-go gen-dart gen-semantics gen-mirror lint spec-lint test test-server test-fixtures test-app \
        web build run up down logs drift-check oasdiff e2e e2e-desktop dist clean

SPEC        := api/openapi.yaml
SPEC_SRC    := api/spec
WEB_DIST    := server/internal/web/dist
APP_WEB_OUT := app/app/build/web

## --- codegen -----------------------------------------------------------------

generate: gen-go gen-dart gen-semantics gen-mirror

# The contract is authored as fragments in api/spec/ (one file per API
# domain); specbundle assembles the single bundled spec that every
# consumer reads. The bundle stays committed; drift-check keeps it fresh.
# Deliberately phony, not an mtime-ruled file target: a fresh checkout
# gives the bundle and the fragments equal mtimes, so a file target could
# skip bundling exactly where drift-check needs it to run. The tool is
# fast and no-ops when output is unchanged; make runs a shared
# prerequisite once per invocation, -j included.
spec-bundle:
	cd server && go run ./cmd/specbundle -src ../$(SPEC_SRC) -out ../$(SPEC)

gen-go: spec-bundle
	cd server && go tool oapi-codegen -config ../tools/oapi-codegen.yaml ../$(SPEC)
	cd server && gofmt -w internal/api/gen.go

gen-dart: spec-bundle
	tools/generate-dart.sh

# The semantics identifiers the e2e suite drives the UI by, emitted into
# the app and the specs from one list so the two cannot drift (the specs
# would otherwise fail as "element not found" rather than as a renamed
# contract). Independent of the OpenAPI bundle.
gen-semantics:
	dart run tools/gen-semantics-ids.dart
	dart format app/app/lib/src/shell/semantics_ids.dart >/dev/null

# The client mirror's drift code (database.g.dart), which is checked in
# like every other generated file and was previously regenerated by
# hand -- so a stale one failed nothing. Named for the mirror, not for
# "drift": `drift-check` below is the codegen-drift gate over every
# generated artifact and has nothing to do with drift the package.
# Independent of the OpenAPI bundle.
#
# Resolves the pub workspace itself rather than inheriting the one
# gen-dart happens to leave behind: build_runner needs a package config
# and this target has to stand up alone, on a fresh checkout and under
# `make -j`, where nothing orders it after gen-dart.
gen-mirror:
	cd app && dart pub get
	cd app/packages/waxdeck_data && dart run build_runner build

# Assets that are generated but rarely regenerated: the bundled type,
# the icon subsets, and the brand kit. Not part of `generate` (they hit
# the network and take minutes); run them when the design changes.
.PHONY: fonts icons brand
fonts:
	tools/fetch-fonts.sh

icons:
	tools/fetch-icons.sh

brand:
	python3 tools/generate-brand.py

## --- quality gates -----------------------------------------------------------

lint: spec-lint
	cd server && go vet ./... && test -z "$$(gofmt -l .)"
	cd server && go run ./cmd/spawnlint ./...
	cd fixtures && go vet ./... && test -z "$$(gofmt -l .)"
	cd app && dart format --set-exit-if-changed app/lib app/test app/integration_test app/tool packages/waxdeck_api/lib packages/waxdeck_api/test packages/waxdeck_player/lib packages/waxdeck_player_testing/lib packages/waxdeck_player_testing/test packages/waxdeck_data/lib packages/waxdeck_data/test packages/waxdeck_ui/lib packages/waxdeck_ui/test packages/waxdeck_ui/example/lib packages/waxdeck_ui/example/test >/dev/null
	cd app && flutter analyze --no-pub

# Lints the committed bundle as-is (lint never mutates the tree);
# bundle freshness against the fragments is drift-check's job.
spec-lint:
	npx --yes @stoplight/spectral-cli lint --fail-severity=warn $(SPEC)

test: test-server test-fixtures test-app

test-server:
	cd server && go test ./...

test-fixtures:
	cd fixtures && go test ./...

test-app:
	cd app/packages/waxdeck_api && dart test
	cd app/packages/waxdeck_ui && flutter test
	cd app/packages/waxdeck_ui/example && flutter test
	cd app/packages/waxdeck_data && flutter test
	cd app/packages/waxdeck_player_testing && flutter test
	cd app/app && flutter test

# Regenerate everything and fail if the tree changes (CI codegen-drift gate).
drift-check: generate
	git diff --exit-code -- $(SPEC) server/internal/api app/packages/waxdeck_api_gen \
		app/app/lib/src/shell/semantics_ids.dart e2e/tests/semantics-ids.ts \
		app/packages/waxdeck_data/lib/src/database.g.dart

# Breaking-change gate against the base ref (override BASE for CI).
# api/oasdiff-allow.txt, when present, lists deliberately accepted
# breaking changes (one oasdiff output line per entry); it is temporary
# by construction and is deleted once the base ref contains the change.
# --flatten-allof diffs the merged (effective) schemas: both generators
# flatten allOf, so a property moving between an allOf branch and its
# base is a no-op on the wire and must not read as a break.
BASE ?= origin/main
OASDIFF_ALLOW := api/oasdiff-allow.txt
oasdiff:
	git show "$(BASE):$(SPEC)" > .oasdiff-base.yaml
	go run github.com/oasdiff/oasdiff@v1.11.7 breaking .oasdiff-base.yaml $(SPEC) --fail-on WARN --flatten-allof \
		$(if $(wildcard $(OASDIFF_ALLOW)),--err-ignore $(OASDIFF_ALLOW) --warn-ignore $(OASDIFF_ALLOW)); \
	status=$$?; rm -f .oasdiff-base.yaml; exit $$status

## --- build -------------------------------------------------------------------

# Flutter web build -> server embed dir (WasmGC target with JS fallback).
web:
	cd app/app && flutter build web --wasm
	rm -rf $(WEB_DIST) && mkdir -p $(WEB_DIST)
	cp -r $(APP_WEB_OUT)/. $(WEB_DIST)/

# The embedded UI's freshness marker and the Flutter sources it is built
# from. WEB_STAMP is a real file (not phony) so it rebuilds only when a
# source is newer, which is what keeps `make run` from serving a stale
# build without paying a Flutter compile on every Go-only iteration.
WEB_STAMP := $(WEB_DIST)/flutter_bootstrap.js
DART_SRCS := $(shell find app/app/lib -name '*.dart' 2>/dev/null) \
             $(shell find app/packages -path '*/lib/*.dart' 2>/dev/null) \
             app/app/pubspec.yaml

$(WEB_STAMP): $(DART_SRCS)
	$(MAKE) web

# Server binary. With the embedded web UI: `make web build` (tag withweb).
# Without (placeholder page only): `make build TAGS=`. `build` embeds
# whatever is in the dist dir and never runs Flutter, so it stays usable
# in Flutter-less environments (CI, packaging).
TAGS ?= withweb
build:
	cd server && go build $(if $(TAGS),-tags $(TAGS)) -o waxdeck ./cmd/waxdeck

# `run` is the fast local path: one binary with the embedded UI and no
# streaming engine. It refreshes the UI when the Dart sources changed,
# and sources a root .env (gitignored) so config persists across runs
# instead of being retyped. Good for iterating on the app; for a full
# realistic instance (streaming engine, the real container topology),
# use `make up`.
run: $(WEB_STAMP)
	$(MAKE) build
	set -a; [ -f .env ] && . ./.env; set +a; ./server/waxdeck

## --- run the full stack (Docker) ---------------------------------------------

COMPOSE := docker compose -f deploy/compose.yaml

# The complete, testable instance: the waxdeck image plus the flavored
# waxflow streaming sidecar, wired over the internal network. Generates
# deploy/.env with fresh internal keys on first run; set WAXDECK_LIBRARY
# in it to point at your music (defaults to an empty deploy/library).
up: deploy/.env deploy/waxflow-config/waxflow.json
	@mkdir -p deploy/library deploy/podcasts
	WAXDECK_UID=$$(id -u) WAXDECK_GID=$$(id -g) $(COMPOSE) up --build -d
	@echo "WaxDeck is up on http://localhost:4420  (make logs / make down)"

# Seed the sidecar's roots config from the committed example, which
# carries the same roots compose.yaml gives WaxDeck (WAXDECK_LIBRARY_ROOTS
# plus the podcast dir). The sidecar reads its roots from a file rather
# than WAXFLOW_ROOTS so a library created at runtime can be reconciled
# without a restart; WaxDeck merges its own roots into the file from then
# on. The file itself is deployment state, so it stays untracked -- like
# deploy/.env, which is seeded the same way. A bare `docker compose up`
# needs this copy first; README documents it beside the .env step.
deploy/waxflow-config/waxflow.json: deploy/waxflow-config.example.json
	@mkdir -p $(@D)
	@cp deploy/waxflow-config.example.json $@
	@echo "wrote $@ (the sidecar's roots; WaxDeck merges runtime libraries into it)"

# Generate deploy/.env from the example with matching internal API keys,
# so the stack comes up without hand-editing secrets.
deploy/.env:
	@key=$$(openssl rand -hex 24); \
	 worker=$$(openssl rand -hex 24); \
	 sed -e "s|^WAXFLOW_API_KEYS=.*|WAXFLOW_API_KEYS=$$key|" \
	     -e "s|^WAXDECK_FLOW_API_KEY=.*|WAXDECK_FLOW_API_KEY=$$key|" \
	     -e "s|^WAXDECK_WORKER_TOKENS=.*|WAXDECK_WORKER_TOKENS=$$worker|" \
	     deploy/.env.example > deploy/.env
	@echo "wrote deploy/.env with generated keys; set WAXDECK_LIBRARY to your music path"

down:
	$(COMPOSE) down

logs:
	$(COMPOSE) logs -f --tail=100

## --- e2e & packaging ----------------------------------------------------------

# The suite drives the real web build through the real binary:
# run-stack.sh starts ./server/waxdeck, which serves the UI embedded at
# link time. So both have to be current or the suite tests the last build
# and fails for reasons that are not in the working tree - a stale bundle
# reads exactly like a missing feature, and the failure lands on whichever
# spec touched it rather than saying so.
#
# WEB_STAMP is the same freshness marker `run` uses: a real file against
# the Dart sources, so a spec-only or Go-only iteration pays no Flutter
# compile. `build` is unconditional and cheap by comparison: it has to run
# whenever the bundle moved, and it is also what heals a binary
# `e2e-desktop` left behind - that runner links without `-tags withweb`,
# so a desktop run followed by this one used to serve the placeholder
# page.
#
# WAXDECK_BASE_URL means the caller is pointing the suite at a stack they
# are running themselves, so neither is ours to rebuild.
e2e:
ifndef WAXDECK_BASE_URL
	$(MAKE) $(WEB_STAMP)
	$(MAKE) build
endif
	cd e2e && npm ci --no-audit --no-fund && npm run typecheck && npx playwright test

# The desktop app journey plus the engine conformance suite against the
# real mpv backend, which is where clip windows and gapless crossings are
# verified for real. Needs a display and an audio sink, so CI does not
# run it; the runner says how to wrap it on a headless box.
e2e-desktop:
	bash e2e/run-desktop.sh

dist:
	docker build -f deploy/Dockerfile -t waxdeck:dev .

clean:
	rm -rf server/waxdeck $(WEB_DIST) app/app/build e2e/test-results e2e/playwright-report
