// Package notices carries the third-party license texts for the Go
// modules linked into the server binary, so any distributed artifact
// answers for itself (`waxdeck --third-party-notices`; the dist image
// also ships the file). The embedded web UI is licensed separately and
// carries its own NOTICES bundle inside its assets; this is the Go
// half. Regenerated by cmd/noticegen via `make generate` and
// drift-checked like every other generated artifact.
package notices

import _ "embed"

// Text is the concatenated notice file; regenerated, never edited.
//
//go:embed third_party_notices.txt
var Text string
