// The rules the type system cannot express, as a ratchet.
//
// Most of what keeps this suite convergent is enforced by `tsc`: a spec
// that reaches for `page.locator` does not compile, because the `page`
// fixtures hand it is a narrowed type without one. What is left over is
// this file - conventions about literals and imports, which no type can
// see - and it is checked against a per-file allowlist that may only
// ever shrink.
//
// Shrink-only is the whole mechanism. A count that comes in under its
// allowance fails as loudly as one that comes in over: "ratchet: lower
// N" is the message, and the fix is one edit. That is what stops a
// migration from stalling half-done, and it is why deleting the last
// offender in a file means deleting its allowlist entry too. A file with
// no entry has no tolerance at all.
//
// AST, not grep: about a fifth of the lines in these specs are comments
// quoting the very code they explain, so a text scan reports the
// explanation as the offence.
//
//   node lint/conformance.mjs                 check
//   node lint/conformance.mjs --write-baseline seed or re-seed the allowlist

import ts from 'typescript';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const e2eRoot = fileURLToPath(new URL('..', import.meta.url));
const allowlistPath = join(e2eRoot, 'lint', 'allowlist.json');
const write = process.argv.includes('--write-baseline');

// Accounts allowed to hold the admin role, pinned here so that granting
// one is a visible edit in a reviewed file rather than a word added to a
// table. Admin is server-global authority: an account that holds it can
// flip switches every other worker shares.
const ADMIN_SHAPES = [
  'admin-console',
  'admin-ops',
  'admin-readonly',
  'artwork',
  'driver-smoke',
  'metadata-workbench',
  'notifications',
  'playlist-sync',
  'review-queue',
  'signup-ui',
  'uploads',
];

// Each exemption states its reason, so that the set is auditable and
// nothing is quietly unaccounted for.
//
// The three spec exemptions are the three files that ask for `rawPage`
// by name. That is the whole set, and it is meant to stay that way: a
// migrated spec drives the app through the driver, and a file that needs
// the real `Page` is one whose subject is not the app - somebody else's
// HTML form, the canvas itself, the accessibility tree the driver is
// forbidden to use, or the platform's own instrumentation.
//
// An exemption names the rules it waives rather than waiving all of
// them. A blanket skip is how `hand-typed-identifier` - which CLAUDE.md
// makes a hard rule and this file applies everywhere, the driver
// included - came to be unenforced in five files that only ever needed
// to be let off the driver rules. `*` is the generated files, where
// every rule is meaningless because nobody writes them.
const EXEMPT = [
  ['tests/semantics-ids.ts', '*', 'generated by make generate'],
  ['tests/api-types.ts', '*', 'generated by make generate'],
  [
    'tests/support/',
    ['force-click', 'numeric-timeout', 'raw-sleep'],
    'raw-page infrastructure: probes the page directly by design',
  ],
  [
    'tests/a11y-audit.spec.ts',
    ['force-click', 'numeric-timeout'],
    'a roles-and-names-only journey is its contract',
  ],
  [
    'tests/perf-',
    ['force-click', 'numeric-timeout', 'raw-sleep', 'admin-identity', 'api-path'],
    'own contexts and platform instrumentation against a separate corpus stack, ' +
      'which the fixtures-bound typed api cannot reach',
  ],
  [
    'tests/desktop-loopback.spec.ts',
    ['numeric-timeout', 'api-path', 'raw-sleep'],
    "drives the test IdP's plain HTML form and a child probe's stdout, not the app",
  ],
];

/// The rules waived for a file, or null if it is held to all of them.
const waived = (file) => {
  const hit = EXEMPT.find(([prefix]) => file.startsWith(prefix));
  return hit === undefined ? null : hit[1];
};

const isWaived = (file, rule) => {
  const rules = waived(file);
  return rules !== null && (rules === '*' || rules.includes(rule));
};

const isSpec = (file) => file.endsWith('.spec.ts');
const isAccounts = (file) => file === 'tests/accounts.ts';
const isFixtures = (file) => file === 'tests/fixtures.ts';
// The two specs whose subject is the bootstrap administrator itself:
// first-run creates it on the shared stack, and admin-wizard creates
// its own on the rootless wizard stack, where no minting authority
// exists until the spec makes one.
const isBootstrapSpec = (file) =>
  file === 'tests/first-run.spec.ts' || file === 'tests/admin-wizard.spec.ts';
const everywhere = () => true;

// A rule says what it forbids, where it applies, and how to fix it.
const RULES = [
  {
    name: 'hand-typed-identifier',
    // Everywhere but the generated registry: an identifier written as a
    // string survives a rename in app/semantics-ids/ and fails later as
    // a missing element rather than as the contract change it is. The
    // driver is held to it too - it is the half that builds locators.
    applies: everywhere,
    fix: 'use SemanticsIds/SemanticsIdPrefixes with sem()/semPrefix()',
  },
  {
    name: 'force-click',
    applies: isSpec,
    fix: 'drive the control through a driver gesture, which owns the forced click',
  },
  {
    name: 'secondary-tap',
    // A right click over canvas is a gesture and not a click. The card
    // it aims at has to be wheeled where a click can land on it first,
    // because flutter clips a part-scrolled node's rect and keeps
    // publishing it - which is how a spec's own `click({ button:
    // 'right' })` on the continue shelf opened the first Never played
    // card's menu two shelves down.
    applies: isSpec,
    fix: 'raise it through a driver gesture; home.openCardMenu and its kind own the secondary tap',
  },
  {
    name: 'numeric-timeout',
    applies: isSpec,
    fix: 'let the driver budget it, or pass { within: T.<tier> } - a tier, not a number',
  },
  {
    name: 'raw-sleep',
    applies: isSpec,
    fix: 'wait for the thing itself, not for a duration',
  },
  {
    name: 'api-path',
    applies: isSpec,
    fix: 'call it through driver/api.ts, which is typed against the spec',
  },
  {
    name: 'helpers-import',
    // helpers.ts is gone. The rule stays as a hard zero everywhere, so
    // that re-creating a shared toolbox of page primitives beside the
    // driver is a lint failure rather than a habit.
    applies: isSpec,
    fix: 'import from driver/ instead; the helpers.ts toolbox is gone for good',
  },
  {
    name: 'legacy-import',
    // Also a hard zero: `legacyTest` no longer exists, and this is what
    // says so if somebody re-adds one.
    applies: isSpec,
    fix: 'migrate the file to the App driver and import { test } from ./fixtures',
  },
  {
    name: 'admin-identity',
    // The bootstrap administrator is the minting authority and the
    // subject of first-run, and nothing else. A spec that logs in as it
    // is a spec sharing state with every other test on the stack.
    //
    // fixtures.ts is where that authority is wired in - the `adminToken`
    // worker fixture is the one caller of `ensureAdmin` - so it is no
    // more an offender than accounts.ts is.
    applies: (file) => !isBootstrapSpec(file) && !isAccounts(file) && !isFixtures(file),
    fix: 'take the `account` fixture, which mints one account for this test',
  },
];

const ruleApplies = (rule, file) => rule.applies(file);

function sourceFiles(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules' || entry.startsWith('.')) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) sourceFiles(full, out);
    else if (entry.endsWith('.ts')) out.push(full);
  }
  return out;
}

/// The findings in one file, as `{ rule: count }`.
function scan(file, text) {
  const src = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true);
  const found = {};
  const hit = (rule) => {
    found[rule] = (found[rule] ?? 0) + 1;
  };

  // A string literal's text, or a template's, whether or not it
  // interpolates: the interpolation is exactly how a hand-typed prefix
  // selector hides.
  const literalText = (node) => {
    if (ts.isStringLiteralLike(node)) return node.text;
    if (ts.isTemplateExpression(node)) {
      return (
        node.head.text +
        node.templateSpans.map((s) => s.literal.text).join('')
      );
    }
    return null;
  };

  // The pointer gestures whose options carry Playwright's `force`.
  const gestureMembers = new Set([
    'click', 'dblclick', 'tap', 'check', 'uncheck', 'setChecked',
    'hover', 'dragTo', 'fill', 'press', 'selectText',
    // mouse.down/up: the raw-pointer spelling of the same gestures,
    // which is where a hand-rolled right click would otherwise hide.
    'down', 'up',
  ]);

  // Whether a property sits directly in the options argument of one of
  // those calls. `data: { force: true }` (a request body) shares the
  // property shape but not the call, and must not match: firing on it
  // teaches authors to launder the field through a shorthand, which
  // silences the rule where it matters.
  const isGestureOption = (property) => {
    const options = property.parent;
    if (!options || !ts.isObjectLiteralExpression(options)) return false;
    const call = options.parent;
    if (!call || !ts.isCallExpression(call)) return false;
    if (!call.arguments.includes(options)) return false;
    return (
      ts.isPropertyAccessExpression(call.expression) &&
      gestureMembers.has(call.expression.name.text)
    );
  };

  const visit = (node) => {
    const text_ = literalText(node);
    if (text_ !== null) {
      if (text_.includes('flt-semantics-identifier')) hit('hand-typed-identifier');
      if (text_.includes('/api/v1/')) hit('api-path');
    }

    // sem('literal') / semPrefix('literal'): the selector helper is
    // right, the argument is a string that should have come from the
    // registry.
    if (ts.isCallExpression(node)) {
      const callee = ts.isIdentifier(node.expression) ? node.expression.text : '';
      if (
        (callee === 'sem' || callee === 'semPrefix') &&
        node.arguments.length > 0 &&
        literalText(node.arguments[0]) !== null
      ) {
        hit('hand-typed-identifier');
      }
      if (callee === 'setTimeout') hit('raw-sleep');
      if (ts.isPropertyAccessExpression(node.expression)) {
        const member = node.expression.name.text;
        if (member === 'waitForTimeout') hit('raw-sleep');
        // `test.setTimeout(240_000)` is a whole-test budget, not a
        // sleep, and it belongs to the J tiers for the same reason the
        // per-step numbers belong to T.
        if (
          member === 'setTimeout' &&
          node.arguments.length > 0 &&
          ts.isNumericLiteral(node.arguments[0])
        ) {
          hit('numeric-timeout');
        }
      }
    }

    if (ts.isPropertyAssignment(node) && ts.isIdentifier(node.name)) {
      // Only inside a gesture call's options: `force` is also an
      // honest JSON body field (the forced-rescan request), and firing
      // on that teaches authors to launder the property through a
      // shorthand, which silences the rule where it matters.
      if (
        node.name.text === 'force' &&
        node.initializer.kind === ts.SyntaxKind.TrueKeyword &&
        isGestureOption(node)
      ) {
        hit('force-click');
      }
      // Same call shape, same reason: `button: 'right'` is a request
      // body's field elsewhere, and only the one inside a gesture's
      // options is aiming a pointer at the canvas.
      if (
        node.name.text === 'button' &&
        ts.isStringLiteralLike(node.initializer) &&
        node.initializer.text === 'right' &&
        isGestureOption(node)
      ) {
        hit('secondary-tap');
      }
      // `timeout` and `within` alike. `within` is what this rule's own
      // fix text points authors at, so leaving it unchecked would hand
      // back every one of the hand-chosen numbers the tiers retired,
      // under the one property name the message advertises. A `T.x`
      // member expression is the point and is not a literal.
      if (
        (node.name.text === 'timeout' || node.name.text === 'within') &&
        ts.isNumericLiteral(node.initializer)
      ) {
        hit('numeric-timeout');
      }
    }

    if (ts.isImportDeclaration(node)) {
      const from = node.moduleSpecifier.getText(src).slice(1, -1);
      if (/(^|\/)helpers(\.js)?$/.test(from)) hit('helpers-import');
      const clause = node.importClause?.namedBindings;
      if (clause && ts.isNamedImports(clause)) {
        for (const el of clause.elements) {
          // `propertyName` when the import is aliased, which every
          // unmigrated spec's is: `{ legacyTest as test }`.
          const imported = (el.propertyName ?? el.name).text;
          if (imported === 'legacyTest') hit('legacy-import');
        }
      }
    }

    if (
      ts.isIdentifier(node) &&
      ['ADMIN_USER', 'ADMIN_PASS', 'ensureAdmin'].includes(node.text) &&
      // Not the property half of `x.ensureAdmin`, which is somebody
      // else's name for something else.
      !(ts.isPropertyAccessExpression(node.parent) && node.parent.name === node)
    ) {
      hit('admin-identity');
    }

    ts.forEachChild(node, visit);
  };
  visit(src);
  return found;
}

/// The account shapes that ask for the admin role, read out of the
/// declaration rather than trusted to a comment.
function adminShapes(text) {
  const src = ts.createSourceFile('accounts.ts', text, ts.ScriptTarget.Latest, true);
  const names = [];
  const visit = (node) => {
    if (
      ts.isVariableDeclaration(node) &&
      ts.isIdentifier(node.name) &&
      node.name.text === 'accountShapes' &&
      node.initializer
    ) {
      const object = ts.isAsExpression(node.initializer)
        ? node.initializer.expression
        : node.initializer;
      if (ts.isObjectLiteralExpression(object)) {
        for (const prop of object.properties) {
          if (!ts.isPropertyAssignment(prop)) continue;
          const key = ts.isStringLiteralLike(prop.name)
            ? prop.name.text
            : prop.name.getText(src);
          if (/['"]admin['"]/.test(prop.initializer.getText(src))) names.push(key);
        }
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(src);
  return names;
}

const failures = [];
const counts = {};

for (const full of sourceFiles(join(e2eRoot, 'tests'))) {
  const file = relative(e2eRoot, full).split(sep).join('/');
  const text = readFileSync(full, 'utf8');

  if (isAccounts(file)) {
    const declared = adminShapes(text).sort();
    const pinned = [...ADMIN_SHAPES].sort();
    const extra = declared.filter((n) => !pinned.includes(n));
    const missing = pinned.filter((n) => !declared.includes(n));
    for (const n of extra) {
      failures.push(
        `${file}: account shape "${n}" takes the admin role, which is not in ` +
          `the pinned set in lint/conformance.mjs`,
      );
    }
    for (const n of missing) {
      failures.push(
        `${file}: pinned admin shape "${n}" no longer asks for the role; ` +
          `drop it from ADMIN_SHAPES in lint/conformance.mjs`,
      );
    }
  }

  if (waived(file) === '*') continue;

  const found = scan(file, text);
  for (const [rule, count] of Object.entries(found)) {
    const spec = RULES.find((r) => r.name === rule);
    if (!spec || !ruleApplies(spec, file) || isWaived(file, rule)) continue;
    counts[file] ??= {};
    counts[file][rule] = count;
  }
}

if (write) {
  writeFileSync(allowlistPath, `${JSON.stringify(sortDeep(counts), null, 2)}\n`);
  const total = Object.values(counts).reduce(
    (sum, rules) => sum + Object.values(rules).reduce((a, b) => a + b, 0),
    0,
  );
  console.log(
    `conformance: baseline written to lint/allowlist.json ` +
      `(${Object.keys(counts).length} files, ${total} findings to retire)`,
  );
  process.exit(failures.length === 0 ? 0 : 1);
}

const allowed = JSON.parse(readFileSync(allowlistPath, 'utf8'));
const files = new Set([...Object.keys(allowed), ...Object.keys(counts)]);
for (const file of [...files].sort()) {
  const rules = new Set([
    ...Object.keys(allowed[file] ?? {}),
    ...Object.keys(counts[file] ?? {}),
  ]);
  for (const rule of [...rules].sort()) {
    const budget = allowed[file]?.[rule] ?? 0;
    const actual = counts[file]?.[rule] ?? 0;
    const how = RULES.find((r) => r.name === rule)?.fix ?? '';
    if (actual > budget) {
      failures.push(
        `${file}: ${rule} x${actual}, allowed ${budget} - ${how}`,
      );
    } else if (actual < budget) {
      failures.push(
        `${file}: ${rule} x${actual}, allowlist still says ${budget} - ` +
          `ratchet: lower it to ${actual}${actual === 0 ? ' (or drop the entry)' : ''}`,
      );
    }
  }
}

if (failures.length > 0) {
  console.error('conformance:');
  for (const f of failures) console.error(`  ${f}`);
  console.error(
    `\n${failures.length} problem(s). The allowlist only ever shrinks; ` +
      `re-seed it with --write-baseline only when adding a rule.`,
  );
  process.exit(1);
}

const remaining = Object.values(allowed).reduce(
  (sum, rules) => sum + Object.values(rules).reduce((a, b) => a + b, 0),
  0,
);
console.log(
  remaining === 0
    ? 'conformance: clean, and the allowlist is empty'
    : `conformance: clean (${remaining} allowed finding(s) left to retire)`,
);

function sortDeep(object) {
  return Object.fromEntries(
    Object.keys(object)
      .sort()
      .map((k) => [
        k,
        typeof object[k] === 'object' && object[k] !== null
          ? sortDeep(object[k])
          : object[k],
      ]),
  );
}
