//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for MediaType.
const (
	Audiobook MediaType = "audiobook"
	Music     MediaType = "music"
	Podcast   MediaType = "podcast"
)

// Valid indicates whether the value is a known member of the MediaType enum.
func (e MediaType) Valid() bool {
	switch e {
	case Audiobook:
		return true
	case Music:
		return true
	case Podcast:
		return true
	default:
		return false
	}
}

// Error Structured error. `code` is a stable machine-readable string (see the API-level description for defined codes); `message` is human-readable and not stable.
type Error struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Message Human-readable explanation (not stable, do not parse).
	Message string `json:"message"`
}

// Health Liveness and version information.
type Health struct {
	// ApiVersion Major API version served under `/api/v1`.
	ApiVersion int `json:"apiVersion"`

	// Status Always `ok` when the server can respond.
	Status string `json:"status"`

	// Version Server build version.
	Version string `json:"version"`
}

// Item defines model for Item.
type Item struct {
	// AddedAt When the item entered the library.
	AddedAt *time.Time `json:"addedAt,omitempty"`

	// Album Album / series / podcast title, when applicable.
	Album *string `json:"album,omitempty"`

	// ArtUrl Origin-relative URL of the item's artwork, when present.
	ArtUrl *string `json:"artUrl,omitempty"`

	// Artist Primary display artist / author / show name.
	Artist *string `json:"artist,omitempty"`

	// DiscNumber Disc number within a multi-disc release (music).
	DiscNumber *int `json:"discNumber,omitempty"`

	// DurationMs Duration in milliseconds.
	DurationMs int64 `json:"durationMs"`

	// Genres Display genres.
	Genres *[]string `json:"genres,omitempty"`

	// MediaType The three first-class media types.
	MediaType MediaType `json:"mediaType"`

	// Pid Type-prefixed ULID.
	Pid string `json:"pid"`

	// Title Display title.
	Title string `json:"title"`

	// TrackNumber Track position within its disc (music).
	TrackNumber *int `json:"trackNumber,omitempty"`

	// Year Release / publication year.
	Year *int `json:"year,omitempty"`
}

// ItemPage One keyset-paginated page of items.
type ItemPage struct {
	// Items Items in stable order.
	Items []ItemSummary `json:"items"`

	// NextCursor Opaque cursor for the next page. Absent on the last page.
	NextCursor *string `json:"nextCursor,omitempty"`
}

// ItemSummary Compact item representation used by list endpoints and client-side library mirrors (~summary row).
type ItemSummary struct {
	// Album Album / series / podcast title, when applicable.
	Album *string `json:"album,omitempty"`

	// ArtUrl Origin-relative URL of the item's artwork, when present.
	ArtUrl *string `json:"artUrl,omitempty"`

	// Artist Primary display artist / author / show name.
	Artist *string `json:"artist,omitempty"`

	// DurationMs Duration in milliseconds.
	DurationMs int64 `json:"durationMs"`

	// MediaType The three first-class media types.
	MediaType MediaType `json:"mediaType"`

	// Pid Type-prefixed ULID.
	Pid string `json:"pid"`

	// Title Display title.
	Title string `json:"title"`
}

// LoginRequest Credentials for local-account login.
type LoginRequest struct {
	// Password Account password.
	Password string `json:"password"`

	// Username Account username.
	Username string `json:"username"`
}

// LoginResponse Established session plus a bearer token for native clients.
type LoginResponse struct {
	// Token Opaque bearer token equivalent to the session cookie. Native clients store it in the OS keychain; web clients ignore it and rely on the cookie.
	Token string `json:"token"`

	// User A WaxDeck account as visible to its owner.
	User User `json:"user"`
}

// MediaType The three first-class media types.
type MediaType string

// PlayInfo Everything a client needs to begin playback of one item.
type PlayInfo struct {
	// DurationMs Duration in milliseconds.
	DurationMs int64 `json:"durationMs"`

	// ExpiresAt When the embedded media token stops being accepted.
	ExpiresAt time.Time `json:"expiresAt"`

	// MimeType MIME type the stream will be served as.
	MimeType string `json:"mimeType"`

	// Pid The resolved item's PID.
	Pid string `json:"pid"`

	// Seekable Whether the stream supports sample-exact seeking.
	Seekable bool `json:"seekable"`

	// Url Origin-relative, media-token-authenticated stream URL. Short TTL; re-request play-info on expiry or a `stream-stale` error.
	Url string `json:"url"`
}

// SessionInfo Whether the caller is authenticated, and as whom.
type SessionInfo struct {
	// Authenticated True when a valid session or token was presented.
	Authenticated bool `json:"authenticated"`

	// User A WaxDeck account as visible to its owner.
	User *User `json:"user,omitempty"`
}

// User A WaxDeck account as visible to its owner.
type User struct {
	// DisplayName Optional display name; falls back to `username`.
	DisplayName *string `json:"displayName,omitempty"`

	// Id Stable user identifier.
	Id string `json:"id"`

	// Roles Assigned roles (`admin`, `user`).
	Roles []string `json:"roles"`

	// Username Login name.
	Username string `json:"username"`
}

// Pid defines model for Pid.
type Pid = string

// InvalidRequest Structured error. `code` is a stable machine-readable string (see the API-level description for defined codes); `message` is human-readable and not stable.
type InvalidRequest = Error

// NotFound Structured error. `code` is a stable machine-readable string (see the API-level description for defined codes); `message` is human-readable and not stable.
type NotFound = Error

// Unauthenticated Structured error. `code` is a stable machine-readable string (see the API-level description for defined codes); `message` is human-readable and not stable.
type Unauthenticated = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	// MediaType Restrict results to one media type.
	MediaType *MediaType `form:"mediaType,omitempty" json:"mediaType,omitempty"`

	// Cursor Opaque keyset cursor from a previous page's `nextCursor`. Omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum items per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in and establish a session
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// End the current session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Inspect the current session
	// (GET /auth/session)
	GetSession(w http.ResponseWriter, r *http.Request)
	// Liveness and version probe
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get one item's detail
	// (GET /items/{pid})
	GetItem(w http.ResponseWriter, r *http.Request, pid Pid)
	// Resolve a playable stream for an item
	// (GET /items/{pid}/play-info)
	GetPlayInfo(w http.ResponseWriter, r *http.Request, pid Pid)
	// Browse library items
	// (GET /library/items)
	ListItems(w http.ResponseWriter, r *http.Request, params ListItemsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "pid" -------------
	var pid Pid

	err = runtime.BindStyledParameterWithOptions("simple", "pid", r.PathValue("pid"), &pid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetItem(w, r, pid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlayInfo operation middleware
func (siw *ServerInterfaceWrapper) GetPlayInfo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "pid" -------------
	var pid Pid

	err = runtime.BindStyledParameterWithOptions("simple", "pid", r.PathValue("pid"), &pid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlayInfo(w, r, pid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "mediaType" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "mediaType", r.URL.Query(), &params.MediaType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "mediaType"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mediaType", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/session", wrapper.GetSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/items/{pid}", wrapper.GetItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/items/{pid}/play-info", wrapper.GetPlayInfo)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/library/items", wrapper.ListItems)

	return m
}

type InvalidRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthenticatedJSONResponse Error

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie *string
}

type Login200JSONResponse struct {
	Body    LoginResponse
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse struct{ InvalidRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie *string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type GetSessionRequestObject struct {
}

type GetSessionResponseObject interface {
	VisitGetSessionResponse(w http.ResponseWriter) error
}

type GetSession200JSONResponse SessionInfo

func (response GetSession200JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemRequestObject struct {
	Pid Pid `json:"pid"`
}

type GetItemResponseObject interface {
	VisitGetItemResponse(w http.ResponseWriter) error
}

type GetItem200JSONResponse Item

func (response GetItem200JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetItem401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetItem401JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetItem404JSONResponse struct{ NotFoundJSONResponse }

func (response GetItem404JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlayInfoRequestObject struct {
	Pid Pid `json:"pid"`
}

type GetPlayInfoResponseObject interface {
	VisitGetPlayInfoResponse(w http.ResponseWriter) error
}

type GetPlayInfo200JSONResponse PlayInfo

func (response GetPlayInfo200JSONResponse) VisitGetPlayInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlayInfo401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetPlayInfo401JSONResponse) VisitGetPlayInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlayInfo404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPlayInfo404JSONResponse) VisitGetPlayInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListItemsRequestObject struct {
	Params ListItemsParams
}

type ListItemsResponseObject interface {
	VisitListItemsResponse(w http.ResponseWriter) error
}

type ListItems200JSONResponse ItemPage

func (response ListItems200JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListItems400JSONResponse struct{ InvalidRequestJSONResponse }

func (response ListItems400JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListItems401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response ListItems401JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Log in and establish a session
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// End the current session
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Inspect the current session
	// (GET /auth/session)
	GetSession(ctx context.Context, request GetSessionRequestObject) (GetSessionResponseObject, error)
	// Liveness and version probe
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Get one item's detail
	// (GET /items/{pid})
	GetItem(ctx context.Context, request GetItemRequestObject) (GetItemResponseObject, error)
	// Resolve a playable stream for an item
	// (GET /items/{pid}/play-info)
	GetPlayInfo(ctx context.Context, request GetPlayInfoRequestObject) (GetPlayInfoResponseObject, error)
	// Browse library items
	// (GET /library/items)
	ListItems(ctx context.Context, request ListItemsRequestObject) (ListItemsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSession operation middleware
func (sh *strictHandler) GetSession(w http.ResponseWriter, r *http.Request) {
	var request GetSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSession(ctx, request.(GetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionResponseObject); ok {
		if err := validResponse.VisitGetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetItem operation middleware
func (sh *strictHandler) GetItem(w http.ResponseWriter, r *http.Request, pid Pid) {
	var request GetItemRequestObject

	request.Pid = pid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetItem(ctx, request.(GetItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetItemResponseObject); ok {
		if err := validResponse.VisitGetItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlayInfo operation middleware
func (sh *strictHandler) GetPlayInfo(w http.ResponseWriter, r *http.Request, pid Pid) {
	var request GetPlayInfoRequestObject

	request.Pid = pid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlayInfo(ctx, request.(GetPlayInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlayInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlayInfoResponseObject); ok {
		if err := validResponse.VisitGetPlayInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListItems operation middleware
func (sh *strictHandler) ListItems(w http.ResponseWriter, r *http.Request, params ListItemsParams) {
	var request ListItemsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListItems(ctx, request.(ListItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListItems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListItemsResponseObject); ok {
		if err := validResponse.VisitListItemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFp7c9w2kv8qXbytslRFzkiON3crV+pKsZWNNpKls+Rka23fEUP2zCACAQYAR5pz6T77VTdADjlDPbKV",
	"7O5ftoZ4NPrx61838CUpTFUbjdq75OhLUgsrKvRo+a9LWdI/JbrCytpLo5Oj5HpdY1ZbnMs7LEF6rODy",
	"9C3s4WQxgdzb7ODwL3/76x/f/cd//fTVd69+/NP1y2///Ye3J389Pr88O8n3J0maSFqnFn6ZpIkWFdJf",
	"skzSxOIvjbRYJkfeNpgmrlhiJYJg3qOlef/9UWT/+/nLy/vs40H2p+Ps+7/8cP7uMrv+Mfvb5y8vv77/",
	"Q5Imfl3Tos5bqRfJ/f09Le1qox3ywU71SihZvsdfGnSefimM9qj5v6KulSwEHXf6s6Mzf+kJ8geL8+Qo",
	"+bfpRnHT8NVNT6w1Nmw31Nm5UHNjKyzBhi1hbyZKKBrrjE1BBnGg034K9HlmyvX+JLlPk3fGf2caXf7+",
	"kr4zwaS30i/BL4Vn40oHK+nkTCF4A36JUAil0LJwH7Ro/BK1J1HwHyNj0JdD56TRYCx4c4MaboWD2qJD",
	"7bGcJDQ1rkabhQV3HPrK26bwjcUSkEZMIC9MiTmdWoDzgo5diWIpNWYWRck/BN+CPYfICjm+PM0UrlBB",
	"b3WYGwslzqXGEmhRt/8a8gqdE4uwwbKphN6sKnQJ2vi46+STTtKktqZG62VwXVpl7AzjUvKBeGeKO7wT",
	"Va0oMrTx2Zw9aidY0iTKt7vL90Nh8a5WQrNpYW8jdQql4UPUwjrc396451+1LOEJwBgJ5j5MfAz62Mj8",
	"uRtvZj9j4ek836NQfrl7nDO5Qo3OsdZXaNmXpKZI5UNNdpQvavljGLe72rn42Vhyg24ph3aFJTS6RAv5",
	"VNRyujrMB/o47MSV2uMCLcnrvPCN293hWN2KtYPc3ORwu0TNfsebWCiEhgBx5VDh5mbMxKuHTnEVlps1",
	"UnU6GS54MDmcHGQlrp40TTzHZre0r8AxS516rFjPSl3Mk6OPjwMEjb5qqkrYdXKfbp/k5M6jLrGEEr2Q",
	"CuYSVelghmujy6C6MBesuR0xdVlieex3NfRTq3n2Y0IaQg76QcmZFXZNawUfSo6SUnjMvKxwzAqldMW7",
	"pprhCCq9la4AzR85WKQGAVWjvMxoGlhUKBzCXtU4WXCU7XrSArVFN7p4rcQawndOyR4rHrgx9Ew16MbE",
	"jj8Ia8Wa/7aiuHnoHNf0EWrjJONEPIr0DvgYj4q/RjGy4vt48inUzazNLUBjB4768uDlq91F73e87vN2",
	"evmuUapzGmMpB0i9UJ192fCT1l0vR5HyQiPc4Nqhz2qxkJoSI9RigWDmPN/telxnguFStIkDqdtMZGyJ",
	"dmCy58fIjuk03vk3zEJGzlCLXxqMJIU1QU5OM/gkEzieUaIFE8JBCRc/cNZ6HBqC7A9BQCvwjkhvTFWL",
	"wofQsxhTfXCAxmEJszUo6TygLmsjtQ/YXiiJ2mdOlhsjVpJSo4O9/+vBwP5YxhVq1lRjaDxrKpgSAEt0",
	"5I2mLEgHXnpKgozQkf1QLh+LJGH9B6tGVG/lQlKmVcLLFcKH92fkOC3qvHAgrL819iZuExUxBOqYcKas",
	"6+kTeXYqrH9AQulGUPDSSlZaGZEkjIMpEBc0lvSyNLdA7H705GVj2WznY+gUv5HTV1Ip6bAwunTD8D58",
	"dXBw0ENaqf3Xr0ZhpMJSimv++fFgOe8G3qdckTxR/Hw4O3071PmvZjNpwu7yMETz5+Eml1bogsjnpdFr",
	"+HYcprcCLtRXG020+w4sMRaPZ2Yhda9Q2gpIiyUxf6EcI4QyhVCZKArTaA+K5u4CXS2cuzV2RL3HcWI7",
	"YpBKu2lpUkl9hnpBpO5wRKWNQxvqyoc2aEcMFSvKSuqnlt9SbLdXuhHwET2GInRXsBNGd+mWuClratVQ",
	"BTJDYbGtcEjJOoBCQLWRRMIjH8TzwXJ0kJVQBOOxsGs3L4y5kTiBd4PNwHljCYQoNmn4xRXluWIppH4N",
	"tzjrBsqFjiMJgS2qdZso4spjWSKY7qkw/eBiJt+2Ay3IZx8zwHkfBbaiekk1nEWEubTOZ4USzgEHC9A6",
	"AXk0ZYGPCRMW0nmAeyK1TSnNzJib3r6bE10qsT7VczNi8xXaNdGhBYioN9CIpSNbzHAhyQXEekYEyszB",
	"aIzUY9vg/0gwxbtaWnSPMmOsZkj0uVUhu5rzpib6zcctCqy5RH8uVa5khePGOz89P2ErBff1FgWVl0rB",
	"DNsSTLitQCeLTedKFGN7jSP/EqnAMmoVu14vHFz+BvDvEG+IH4yq0y/R9o/lmro2lsKQd8zwjtgQLSH1",
	"opdnZ8YoFJoD6hn8Ig2GythQ2aCb0+784f3ZBK6Wxnq4vj57DRaztpVFPppR2UwBzu6xBqbNeZibOS8U",
	"5rG5wmHfIym88zSM/M9alt88ocNPzcHBy68r/42YFYcvv3pm4iMt9JxokPV6Nui79xiGXAVwHA/nvr1C",
	"e4w7SH1tpgyGwsHt0ozE8U4fbbuUajDSymc2wEYd4u9F2KF0Y+r54MYqwGP4Sdy9xeIGWl4gBu1EqgXN",
	"rQ5FzRawBRL0bjSXX/B/hOo4KKXh1zAXSjlg0PQG8jY/56M0dCzSYy+NJoJkdjOXOKwtk8b96kC3Ro2V",
	"4sfOyYXGEvg77OVMQvI0SB775bvFeUtVnizOH+ZCzEjgYRb0RAXHYbUhP+F4u17BEFc0Vvr1FXlX0EEg",
	"IcfNWFvuEm1W4koWCNZQcacXQ9KyNyRArCL2XPZ0HrkRf+l9TXoIrGN8x++9ry+0WsOVqPBKevzmTNxt",
	"MSHYu8XZ5vYi/Li5v7gVdyUWN/8TJ232F7X8AdehjS0jbhRGe1FwBo3TY4REpApSu6PpdCH9splNClNN",
	"3xiFVzXZAu20Hb/TG/+OCUwtrF/D+5Ora25IEmmMM44iyVPzbGkcdyWUWKNNN4Wx0GKBNv2kCasq9KIU",
	"XgChhEKPoRPAJChtS14Xca3lQW7ySX/SbxpridK4wtR4BEvuwtLIPiZyn9Q3s83+M2tuHaahxg9tmChL",
	"l2gmwNQJXGPnokBYIjFN4soWhQJSr6XEyPcXSpDQVCwDckuQpKNs7paipogLfRqIfRppdMp0oqT07tI2",
	"/Q6uCKAyJZJYXYUemM6H92duH4RFUEaUGfkiee/cmgpKQQwYg2qMXpECjHZHn3QGx0r1WhaKFtzqGsOe",
	"X0oHpSmaCrV/4SAPnV+XA2pv1/sTWuiUlLYBLcKTWpZ5kMnvFK/03dssB27hpZALleXADY/0kwbIBX0M",
	"tX0KeV1keWvzFHKssxywls6UmEI+u6GxrQ8Eec6GzZjGIZhQhkSth+4SyRH+l4PUKeSbvlQOpvH7LI3G",
	"FVow87lD73j5k9DDocOJ0Bwna+X8cw4hmz3rOoeWD0D3mkQiv1Xr4c3NEeTxnq5lPgzSw8uvPKhtbuxM",
	"liUyjnd3LfRHYfRcyYLnEqu2Wqg8hM8e5W2mq7HXFoVCUTEEWlkucH+LVU3gHd4GAaESaxB1jcK+7sqw",
	"qnEeaIKn1Rp9o82tjuOFi8ZgXZ53HgwWfWN1aKfFu632fretZiaNVdGtuhgIFSRLHW4RDNPMGEKiwvhD",
	"iEseQwaTjjcQsStPReSH08ATlSwwlssRKM9Pr3dA0tSonWlsgRNjF9M4yU1p7KbB0mIsbda7k4gXGjSQ",
	"1hG1TI6SryYHk6+4ovdLzldTsvKU+xncwTBjzZBNDc+eFtMHnYscNrjmVp7Iocs9DxTcFDKd/tpIijW1",
	"CBobNggIa3woVrjXwNfIILXzND52EdvN3uIKlakrxmnfzI5A6DVoozOsar+Gotff4SiLhRsLUIm67RrM",
	"Gql8JjWUvQWJHUzgPUFyy/ycN1YsMA1sJ/j9xenbN5ReMEB1sDyxQAbj07KlKvF9ADr/rSnXv9k186DB",
	"dT+kOd42uP124OXBwW+9d2wKjVx1x4IDcNMeIgqyRFHGNxpX6LM3gYzsOOQj3vYI0+noFIu/85TiPk1e",
	"BRWMnaxT1XTrjQVPO3x62vZrgj6BTI4+fk4T194OkFuADBHWKWgTecTBxMK1pUvymZbqAtk0/uFIfo8r",
	"c4MhZLtyqlPTXmSExg5Cbz/eNaCwbrSVdtUUBbd3cIUa5By06cZQcioo8B9wfxJ3xxFfjd3fRofR5a9y",
	"lROue8sRgHqeU9z37XISobxoGeCTBmlHHH1JFjhqEMpIVDc/WWOTFVLSrjNp3wwvXASkLQ+L6zhYoId8",
	"8OmIikmHecrPGQS8OjicwJsBMNPu/PDB+obRsMRClrgR1ISLEL4h44LLFRZRj5n5z+ivOk39bpjT72GM",
	"IM6boc3oaB4nj4bhqXY1Mt1+psmX3YOMUWNvG0i17zRqa2ZIGSU0wXrPH9onFy2J6D/DkC3XeEDn8XnI",
	"76jyuMMovrP40sXyaP24pkdfrLBWeop2a+exiqoOl39falneP6jvZ154j6iO32ukg1eDD7zZ2AyZXsqS",
	"b91/N3WzVCPKvl7i5u7+70tGNO/V0/O693pDXPwz+q6L/8JFlfcsF/W9a7ppV/o+iZD42KUC41R3qXBE",
	"ll4a67Pr67M0kvPNpfOm8wt7vf7wdkfTGb4OcrwsF1ezNcyILOafmoODrwouCfm/mAMqJG7oUuC78tDn",
	"iUTw7dm7Y7CUuSxyChUeCqH5ZRnqEmIq2083kc+1UiV8WCA0nzcQPdqkjg3U3ulizxfiC4cIKU4uNNHe",
	"7XprlzLbqHoBt6hU1r30jPz7dmlcuMJvnyQEqKS6cI0+k1UdlELpd9APzydAPvuTuPtOmdtYAcJcKuXi",
	"FZzRBfZqRCVCe2MsVrt7qH+5eO0kGwPIYCa+eWm6J5X+nx3J78NNEIiN10eHYgDVLF0vstuQi6EdA33a",
	"NXZHQ/qH7QdE/LTFzAe47FIwsRGu1uQb4T3abN27v5zAhS2RW1HStS2QvfhOxfMDElnuUyS37ZjQanE3",
	"sqaoKJtg2tGCMdbxAlwllNpUgoXwQplF58LfSp2RCphx8SewWCtRIDsze3LvFR3wnWO8u3zQr8+k4yTk",
	"dr16Gx6JrBaePKlRntGQoLinpLa1+0uDdr3p7PbfTDzPn3vPSHafJV6MtL9C0S6o1FhJ0zh+RvXCDdpg",
	"E7iopO+8ny+qe8+txiQPiz9K3NPdV6x3smqq4FpQow17PLCDkpX0gw1KnItG+eTo8OAgTaqwWnL0R/5L",
	"6vDXyKvX350Q8Du9EYC50Lj9MO+fUeF2yPItt7+HIT5OEYY88cvghuPjZzJt/5bl42dScewZjwTIlagw",
	"i/05Ys/WGH5PFlptsQ3NeSCKsnOJwgQ2trs4g7Z3B5ONw0Ruuut3bd26dTWwV27hzevQ4o/9JNfrG+33",
	"tuFaY3eTqFsSUcaaZaDnSd+zg553F2mhfwv4w/un7WU63L//fP//AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
