// Command noticegen assembles the third-party license notices for the
// server binary: every license, notice, copying, and patent-grant file
// of every module in the build graph of ./cmd/waxdeck, plus the Go
// toolchain's, concatenated into one text file that internal/notices
// embeds and `waxdeck --third-party-notices` prints. Permissive
// licenses (all of them, per ADR-0037) require exactly this: their
// text accompanying binary distributions.
//
// The module set is unioned across every OS a binary is built for,
// because build constraints make the linked set GOOS-conditional and
// the ambient OS alone would under-report a cross-compiled binary.
//
// Run under GOWORK=off (the Makefile does) so the module set and the
// license texts come from the pinned module zips, identical on every
// machine, rather than from whatever workspace checkouts sit nearby.
//
// Run as: go run ./cmd/noticegen -out internal/notices/third_party_notices.txt
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"
	"unicode/utf8"
)

const header = "Third-party license notices for the WaxDeck server binary.\n" +
	"Generated by noticegen from the build graph of ./cmd/waxdeck; DO NOT EDIT.\n" +
	"Regenerate with `make generate`. The embedded web UI is covered\n" +
	"separately, by the NOTICES bundle inside its own assets.\n"

// licenseName matches the file names license texts travel under,
// including suffixed forms (LICENSE.md, LICENSE-3RD-PARTY.md, goja's
// ftoa/LICENSE_LUCENE) and the PATENTS grants the golang.org/x modules
// ship beside their license. Go sources slip the name pattern
// (license_test.go) and are excluded by extension; REUSE-style
// LICENSES/ directories are handled by parent-directory name instead.
var licenseName = regexp.MustCompile(`(?i)^(license|licence|copying|notice|patents)([._-].*)?$`)

var separator = "\n" + strings.Repeat("=", 80) + "\n"

func main() {
	out := flag.String("out", "", "output file (required)")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "noticegen: -out is required")
		os.Exit(2)
	}
	if err := run(*out); err != nil {
		fmt.Fprintln(os.Stderr, "noticegen:", err)
		os.Exit(1)
	}
}

type pkg struct {
	Standard bool
	Module   *struct {
		Path string
		Dir  string
		Main bool
	}
}

// listModules resolves the modules linked into ./cmd/waxdeck for one
// target OS and folds them into mods.
func listModules(goos string, mods map[string]string) error {
	list := exec.Command("go", "list", "-deps", "-json=Standard,Module", "./cmd/waxdeck")
	list.Env = append(os.Environ(), "GOOS="+goos)
	list.Stderr = os.Stderr
	raw, err := list.Output()
	if err != nil {
		return fmt.Errorf("go list -deps (GOOS=%s): %w", goos, err)
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	for dec.More() {
		var p pkg
		if err := dec.Decode(&p); err != nil {
			return fmt.Errorf("decoding go list output: %w", err)
		}
		if p.Standard || p.Module == nil || p.Module.Main {
			continue
		}
		if p.Module.Dir == "" {
			return fmt.Errorf("module %s has no local directory; run `go mod download` first", p.Module.Path)
		}
		mods[p.Module.Path] = p.Module.Dir
	}
	return nil
}

func run(out string) error {
	// The docker image is linux; the other two are what operators build
	// from source and what the flag is expected to answer for there.
	mods := map[string]string{}
	for _, goos := range []string{"linux", "darwin", "windows"} {
		if err := listModules(goos, mods); err != nil {
			return err
		}
	}

	var b strings.Builder
	b.WriteString(header)
	block := func(title string, text []byte) {
		b.WriteString(separator)
		b.WriteString(title)
		b.WriteString("\n\n")
		b.Write(bytes.TrimRight(text, "\n"))
		b.WriteString("\n")
	}

	goroot, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return fmt.Errorf("go env GOROOT: %w", err)
	}
	gorootDir := strings.TrimSpace(string(goroot))
	goLicense, err := os.ReadFile(filepath.Join(gorootDir, "LICENSE"))
	if err != nil {
		return fmt.Errorf("reading the Go toolchain license: %w", err)
	}
	block("Go standard library and runtime", goLicense)
	// The toolchain's patent grant is part of its terms; required, not
	// best-effort, so its absence cannot silently drift the output.
	goPatents, err := os.ReadFile(filepath.Join(gorootDir, "PATENTS"))
	if err != nil {
		return fmt.Errorf("reading the Go toolchain patent grant: %w", err)
	}
	block("Go standard library and runtime (PATENTS)", goPatents)

	for _, path := range slices.Sorted(maps.Keys(mods)) {
		dir := mods[path]
		var files []string
		err := filepath.WalkDir(dir, func(p string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				// testdata is never compiled, and modernc.org/libc vendors
				// a GPL-licensed test corpus there that must not read as a
				// notice for shipped code.
				if d.Name() == "testdata" {
					return filepath.SkipDir
				}
				return nil
			}
			inLicensesDir := strings.EqualFold(filepath.Base(filepath.Dir(p)), "licenses")
			if (!licenseName.MatchString(d.Name()) && !inLicensesDir) ||
				strings.HasSuffix(d.Name(), ".go") {
				return nil
			}
			files = append(files, p)
			return nil
		})
		if err != nil {
			return fmt.Errorf("walking %s: %w", path, err)
		}
		sort.Strings(files)
		appended := 0
		for _, f := range files {
			text, err := os.ReadFile(f)
			if err != nil {
				return err
			}
			rel, err := filepath.Rel(dir, f)
			if err != nil {
				return err
			}
			// The name pattern can catch non-text (a license_banner.png);
			// binary bytes must not land in the notices. Visible, not
			// silent, in case a real license ever ships in an odd encoding.
			if !utf8.Valid(text) {
				fmt.Fprintf(os.Stderr, "noticegen: %s: skipping %s: not UTF-8 text\n", path, filepath.ToSlash(rel))
				continue
			}
			block(path+" ("+filepath.ToSlash(rel)+")", text)
			appended++
		}
		if appended == 0 {
			// A dependency shipping no license text at all is a problem to
			// look at, not to paper over.
			return fmt.Errorf("module %s: no license text found", path)
		}
	}

	final := []byte(b.String())
	if old, err := os.ReadFile(out); err == nil && bytes.Equal(old, final) {
		return nil
	}
	// Same write discipline as specbundle: temp in the target dir,
	// sync, rename.
	tmp, err := os.CreateTemp(filepath.Dir(out), ".noticegen-*.txt")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(final); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmp.Name(), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), out)
}
