// Emits the app's own version as a Dart constant, from the one place it
// is declared.
//
// The About screen reports what build somebody is running, which is the
// first thing a self-hoster is asked for in a bug report. Flutter exposes
// no version at runtime without a plugin, and typing the number into a
// second file is a number that goes stale the first time the pubspec's
// changes - so it is generated, checked in, and drift-gated like every
// other generated artifact.
//
//   dart run tools/gen-app-version.dart        (via `make generate`)
//
// Uses only dart: libraries, so it runs without a package resolution.
import 'dart:io';

const _pubspec = 'app/app/pubspec.yaml';
const _out = 'app/app/lib/src/shell/app_version.dart';

void main() {
  final root = Directory.current.path;
  final pubspec = File('$root/$_pubspec');
  if (!pubspec.existsSync()) {
    stderr.writeln('gen-app-version: run from the repository root');
    exit(2);
  }

  String? version;
  for (final line in pubspec.readAsLinesSync()) {
    // Top-level `version:` only, so a dependency's pinned version can
    // never be mistaken for the app's: a nested key is indented.
    if (!line.startsWith('version:')) continue;
    version = line.substring('version:'.length).trim();
    break;
  }
  if (version == null || version.isEmpty) {
    stderr.writeln('gen-app-version: $_pubspec declares no version');
    exit(1);
  }

  // `1.2.3+45` is a version and a build number. The build number is what
  // the stores increment and says nothing to a listener, so About shows
  // the version and the constant keeps both.
  final plus = version.indexOf('+');
  final semver = plus == -1 ? version : version.substring(0, plus);
  final build = plus == -1 ? '' : version.substring(plus + 1);

  File('$root/$_out').writeAsStringSync('''
// GENERATED by tools/gen-app-version.dart from $_pubspec. Do not edit.
//
// Regenerate with `make generate`; `make drift-check` fails on drift.

/// The app version, as the pubspec declares it.
const String kAppVersion = '$semver';

/// The build number beside it, empty when the pubspec carries none.
const String kAppBuild = '$build';

/// Both, as About draws them.
String get appVersionLabel =>
    kAppBuild.isEmpty ? kAppVersion : '\$kAppVersion (\$kAppBuild)';
''');
  stdout.writeln('gen-app-version: $version -> $_out');
}
