// Generates the semantics-identifier registry the app and the e2e suite
// both compile against.
//
// The identifiers Flutter renders as `flt-semantics-identifier` are the
// contract the browser-driven suite steers by. Written as literals in two
// places, that contract drifts silently: a renamed widget id fails a spec
// with "element not found" instead of "you renamed the contract". So one
// list (app/semantics-ids.json) emits both sides.
//
//   dart run tools/gen-semantics-ids.dart        (via `make generate`)
//
// Uses only dart: libraries, so it runs without a package resolution.
import 'dart:convert';
import 'dart:io';

const _dartOut = 'app/app/lib/src/shell/semantics_ids.dart';
const _tsOut = 'e2e/tests/semantics-ids.ts';
const _source = 'app/semantics-ids.json';

void main(List<String> args) {
  final root = Directory.current.path;
  final file = File('$root/$_source');
  if (!file.existsSync()) {
    stderr.writeln('gen-semantics-ids: run from the repository root');
    exit(2);
  }

  final data = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final groups = (data['groups']! as List<dynamic>).cast<Map<String, dynamic>>();

  final seen = <String, String>{};
  for (final group in groups) {
    for (final entry in (group['ids']! as List<dynamic>)
        .cast<Map<String, dynamic>>()) {
      final name = entry['name']! as String;
      final id = entry['id']! as String;
      final previous = seen[name];
      if (previous != null) {
        stderr.writeln(
          'gen-semantics-ids: "$name" is declared twice ($previous and $id)',
        );
        exit(1);
      }
      seen[name] = id;
      final params = ((entry['params'] as List<dynamic>?) ?? const <dynamic>[])
          .cast<String>();
      for (final param in params) {
        if (!id.contains('{$param}')) {
          stderr.writeln(
            'gen-semantics-ids: "$name" declares $param, which "$id" '
            'never uses',
          );
          exit(1);
        }
      }
      final placeholders = RegExp(r'\{([a-zA-Z0-9_]+)\}')
          .allMatches(id)
          .map((m) => m.group(1)!)
          .toSet();
      final missing = placeholders.difference(params.toSet());
      if (missing.isNotEmpty) {
        stderr.writeln(
          'gen-semantics-ids: "$name" uses ${missing.join(', ')} without '
          'declaring them in params',
        );
        exit(1);
      }
    }
  }

  final dart = _dart(groups);
  final typescript = _typescript(groups);
  // Nothing may reach the output still shaped like a placeholder: an
  // interpolation that failed to substitute compiles fine and ships an
  // identifier no element carries, which the specs would report as a
  // missing element rather than as a generator fault.
  for (final output in <String>[dart, typescript]) {
    // A brace preceded by `$` is an interpolation that did substitute.
    final leftover = RegExp(r'(?<!\$)\{[a-zA-Z0-9_]+\}').firstMatch(output);
    if (leftover != null) {
      stderr.writeln(
        'gen-semantics-ids: "${leftover.group(0)}" survived substitution',
      );
      exit(1);
    }
  }

  File('$root/$_dartOut').writeAsStringSync(dart);
  File('$root/$_tsOut').writeAsStringSync(typescript);
  stdout.writeln(
    'gen-semantics-ids: ${seen.length} identifiers -> $_dartOut, $_tsOut',
  );
}

String _dart(List<Map<String, dynamic>> groups) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by `make generate` from $_source. Do not edit.')
    ..writeln('//')
    ..writeln('// The semantics identifiers this app exposes. Every')
    ..writeln('// `Semantics(identifier:)` in the client reads from here, and')
    ..writeln('// the e2e suite compiles against the same list in')
    ..writeln('// e2e/tests/semantics-ids.ts, so the two cannot drift.')
    ..writeln()
    ..writeln('/// Stable identifiers for the controls the e2e suite drives.')
    ..writeln('abstract final class SemanticsIds {');

  for (final group in groups) {
    final doc = group['doc'] as String? ?? '';
    buffer
      ..writeln()
      ..writeln('  // ${group['name']}: $doc');
    for (final entry in (group['ids']! as List<dynamic>)
        .cast<Map<String, dynamic>>()) {
      final name = entry['name']! as String;
      final id = entry['id']! as String;
      final params = ((entry['params'] as List<dynamic>?) ?? const <dynamic>[])
          .cast<String>();
      if (params.isEmpty) {
        buffer.writeln("  static const String $name = '$id';");
      } else {
        final signature = params.map((p) => 'Object $p').join(', ');
        buffer.writeln("  static String $name($signature) => '${_dartBody(id)}';");
      }
    }
  }

  buffer.writeln('}');
  return buffer.toString();
}

/// Interpolates the placeholders for Dart, bracing a name only where the
/// next character would otherwise be read as part of it.
///
/// The following character is inspected rather than matched, because a
/// pattern can put two placeholders side by side: consuming the character
/// after `{a}` in `{a}{b}` would eat the opening brace of `{b}` and leave
/// it in the output as literal text.
String _dartBody(String id) => id.replaceAllMapped(
  RegExp(r'\{([a-zA-Z0-9_]+)\}'),
  (m) {
    final next = m.end < id.length ? id[m.end] : '';
    final name = m.group(1);
    return RegExp(r'[A-Za-z0-9_]').hasMatch(next)
        ? r'${' '$name}'
        : r'$' '$name';
  },
);

String _typescript(List<Map<String, dynamic>> groups) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by `make generate` from $_source. Do not edit.')
    ..writeln('//')
    ..writeln('// The semantics identifiers the app exposes as')
    ..writeln('// flt-semantics-identifier attributes. Import these rather')
    ..writeln('// than writing the strings: a rename then fails to compile')
    ..writeln('// here instead of failing as a missing element at runtime.')
    ..writeln()
    ..writeln('export const SemanticsIds = {');

  for (final group in groups) {
    final doc = group['doc'] as String? ?? '';
    buffer
      ..writeln()
      ..writeln('  // ${group['name']}: $doc');
    for (final entry in (group['ids']! as List<dynamic>)
        .cast<Map<String, dynamic>>()) {
      final name = entry['name']! as String;
      final id = entry['id']! as String;
      final params = ((entry['params'] as List<dynamic>?) ?? const <dynamic>[])
          .cast<String>();
      if (params.isEmpty) {
        buffer.writeln("  $name: '$id',");
      } else {
        final signature = params.map((p) => '$p: string | number').join(', ');
        var body = id;
        for (final param in params) {
          body = body.replaceAll('{$param}', '\${$param}');
        }
        buffer.writeln('  $name: ($signature) => `$body`,');
      }
    }
  }

  buffer
    ..writeln('} as const;')
    ..writeln()
    ..writeln('/// The attribute selector Flutter renders an identifier as.')
    ..writeln("export const sem = (id: string) =>")
    ..writeln('  `[flt-semantics-identifier="\${id}"]`;');
  return buffer.toString();
}
