// GENERATED by tools/gen-app-version.dart from app/app/pubspec.yaml. Do not edit.
//
// Regenerate with `make generate`; `make drift-check` fails on drift.

/// The app version, as the pubspec declares it.
const String kAppVersion = '0.1.0';

/// The build number beside it, empty when the pubspec carries none.
const String kAppBuild = '1';

/// Both, as About draws them.
String get appVersionLabel =>
    kAppBuild.isEmpty ? kAppVersion : '$kAppVersion ($kAppBuild)';
