// GENERATED by `make generate` from app/semantics-ids.json. Do not edit.
//
// The semantics identifiers this app exposes. Every
// `Semantics(identifier:)` in the client reads from here, and
// the e2e suite compiles against the same list in
// e2e/tests/semantics-ids.ts, so the two cannot drift.

/// Stable identifiers for the controls the e2e suite drives.
abstract final class SemanticsIds {
  // admin: The admin console: users, settings, schedules, backups, trash, audit, migration.
  static const String adminAudit = 'admin-audit';
  static const String adminBackups = 'admin-backups';
  static const String adminMigrate = 'admin-migrate';
  static const String adminSettingsSection = 'admin-settings-section';
  static const String adminTrash = 'admin-trash';
  static const String adminUsers = 'admin-users';
  static const String auditFilter = 'audit-filter';
  static String auditRow(Object id) => 'audit-row-$id';
  static const String backupCreate = 'backup-create';
  static const String backupImport = 'backup-import';
  static String backupRow(Object id) => 'backup-row-$id';
  static const String inviteCreate = 'invite-create';
  static String inviteRevoke(Object id) => 'invite-revoke-$id';
  static String inviteRow(Object id) => 'invite-row-$id';
  static const String inviteToken = 'invite-token';
  static const String migratePassword = 'migrate-password';
  static const String migrateServerUrl = 'migrate-server-url';
  static const String migrateSource = 'migrate-source';
  static const String migrateSubmit = 'migrate-submit';
  static const String migrateToken = 'migrate-token';
  static const String migrateUsername = 'migrate-username';
  static String requestApprove(Object id) => 'request-approve-$id';
  static String requestReject(Object id) => 'request-reject-$id';
  static String requestRow(Object id) => 'request-row-$id';
  static const String restoreBanner = 'restore-banner';
  static const String restoreCancel = 'restore-cancel';
  static String scheduleCron(Object kind) => 'schedule-cron-$kind';
  static String scheduleEnabled(Object kind) => 'schedule-enabled-$kind';
  static String scheduleRow(Object kind) => 'schedule-row-$kind';
  static String scheduleSave(Object kind) => 'schedule-save-$kind';
  static const String settingReadOnly = 'setting-read-only';
  static const String settingSignupEnabled = 'setting-signup-enabled';
  static const String settingSonicAnalysis = 'setting-sonic-analysis';
  static const String signupRequests = 'signup-requests';
  static const String trashEmpty = 'trash-empty';
  static String trashPurge(Object id) => 'trash-purge-$id';
  static String trashRestore(Object id) => 'trash-restore-$id';
  static String trashRow(Object id) => 'trash-row-$id';
  static String userRow(Object id) => 'user-row-$id';

  // auth: Sign-in, first-run setup, and signup. The names here are frozen vocabulary for the accessibility audit.
  static const String loginError = 'login-error';
  static const String loginPassword = 'login-password';
  static const String loginSubmit = 'login-submit';
  static const String loginUsername = 'login-username';
  static String oidcLogin(Object id) => 'oidc-login-$id';
  static const String setupConfirm = 'setup-confirm';
  static const String setupDisplayName = 'setup-display-name';
  static const String setupError = 'setup-error';
  static const String setupPassword = 'setup-password';
  static const String setupSubmit = 'setup-submit';
  static const String setupUsername = 'setup-username';
  static const String signupError = 'signup-error';
  static const String signupInviteToken = 'signup-invite-token';
  static const String signupOpen = 'signup-open';
  static const String signupPassword = 'signup-password';
  static const String signupResult = 'signup-result';
  static const String signupSubmit = 'signup-submit';
  static const String signupUsername = 'signup-username';

  // books: Audiobooks: the book screen, its chapters, and its per-book settings.
  static const String bookResume = 'book-resume';
  static const String bookSettingsOpen = 'book-settings-open';
  static const String bookSettingsSave = 'book-settings-save';
  static const String bookSettingsSpeed = 'book-settings-speed';
  static const String bookToolsMenu = 'book-tools-menu';
  static String chapter(Object index) => 'chapter-$index';

  // connect: Connect: endpoints, remote sessions, and cast controls.
  static String endpoint(Object id) => 'endpoint-$id';
  static const String remoteNext = 'remote-next';
  static const String remotePlayHere = 'remote-play-here';
  static const String remotePrevious = 'remote-previous';
  static const String remoteSeek = 'remote-seek';
  static const String remoteToggle = 'remote-toggle';
  static const String remoteVolume = 'remote-volume';
  static String session(Object id) => 'session-$id';

  // deck: The deck bar, the side panel it opens, and the shell's lifecycle banners.
  static const String bannerReconnecting = 'banner-reconnecting';
  static const String bannerUpdated = 'banner-updated';
  static const String bannerUpdatedReload = 'banner-updated-reload';
  static const String deckBar = 'deck-bar';
  static const String deckCast = 'deck-cast';
  static const String deckMore = 'deck-more';
  static const String deckNext = 'deck-next';
  static const String deckOffer = 'deck-offer';
  static const String deckOfferDismiss = 'deck-offer-dismiss';
  static const String deckOfferResume = 'deck-offer-resume';
  static const String deckPlay = 'deck-play';
  static const String deckPrevious = 'deck-previous';
  static const String deckQueue = 'deck-queue';
  static const String deckRepeat = 'deck-repeat';
  static const String deckSeek = 'deck-seek';
  static const String deckShuffle = 'deck-shuffle';
  static const String deckSkipBack = 'deck-skip-back';
  static const String deckSkipForward = 'deck-skip-forward';
  static const String deckStar = 'deck-star';
  static const String panel = 'panel';
  static const String panelClose = 'panel-close';
  static const String queueClear = 'queue-clear';
  static String queueEntry(Object queueId) => 'queue-entry-$queueId';
  static String queueEntryRemove(Object queueId) =>
      'queue-entry-remove-$queueId';
  static const String queueRepeat = 'queue-repeat';
  static const String queueShuffle = 'queue-shuffle';

  // discovery: Instant mixes, similar tracks, and the track lists they open.
  static const String instantMixRun = 'instant-mix-run';
  static const String mixAdventurousness = 'mix-adventurousness';
  static String scopedItem(Object scope, Object index) => '$scope-item-$index';

  // health: Library health: rules, issues, and their fixes.
  static const String adminDiagnostics = 'admin-diagnostics';
  static String duplicateGroup(Object pid) => 'duplicate-group-$pid';
  static String duplicateMerge(Object pid) => 'duplicate-merge-$pid';
  static String health(Object rule) => 'health-rule-$rule';
  static String healthFix(Object rule) => 'health-fix-$rule';
  static String healthIssue(Object pid) => 'health-issue-$pid';
  static const String healthScore = 'health-score';
  static const String healthSweep = 'health-sweep';
  static const String healthWarmingUp = 'health-warming-up';
  static String upgradeGroup(Object itemPid) => 'upgrade-group-$itemPid';
  static String upgradeResolve(Object itemPid) => 'upgrade-resolve-$itemPid';

  // library: Browse and the library grid, including the per-item cards the sync specs drive.
  static const String addToLibrary = 'add-to-library';
  static String browseBucket(Object dimension, Object index) =>
      'browse-$dimension-$index';
  static String browseItem(Object index) => 'browse-item-$index';
  static const String browseOpen = 'browse-open';
  static String browseTab(Object wireName) => 'browse-tab-$wireName';
  static const String curationAudit = 'curation-audit';
  static const String curationBackups = 'curation-backups';
  static const String curationDiagnostics = 'curation-diagnostics';
  static const String curationHealth = 'curation-health';
  static const String curationMenu = 'curation-menu';
  static const String curationMigrate = 'curation-migrate';
  static const String curationOrganize = 'curation-organize';
  static const String curationReview = 'curation-review';
  static const String curationTasks = 'curation-tasks';
  static const String curationTrash = 'curation-trash';
  static const String curationUploads = 'curation-uploads';
  static const String curationUsers = 'curation-users';
  static String item(Object pid) => 'item-$pid';
  static const String itemDelete = 'item-delete';
  static const String itemDeleteConfirm = 'item-delete-confirm';
  static const String offlineBanner = 'offline-banner';
  static const String openStats = 'open-stats';
  static const String playlistsOpen = 'playlists-open';
  static const String podcastsOpen = 'podcasts-open';
  static const String radioOpen = 'radio-open';
  static const String resumeBanner = 'resume-banner';
  static const String settingsOpen = 'settings-open';

  // metadata: The metadata editor: fields, locks, candidates, and artwork.
  static const String creditsRole = 'credits-role';
  static const String creditsSave = 'credits-save';
  static String fieldLock(Object name) => 'field-lock-$name';
  static const String lyricsClear = 'lyrics-clear';
  static const String lyricsSave = 'lyrics-save';
  static const String metadataEnrich = 'metadata-enrich';
  static const String metadataForce = 'metadata-force';
  static const String metadataLock = 'metadata-lock';
  static const String metadataRematch = 'metadata-rematch';
  static const String metadataSave = 'metadata-save';
  static const String metadataWriteback = 'metadata-writeback';
  static const String tagAdd = 'tag-add';
  static String tagRemove(Object key) => 'tag-remove-$key';
  static const String unofficialSwitch = 'unofficial-switch';

  // organize: Organize: previews, duplicates, and upgrade groups.
  static const String organizeApply = 'organize-apply';
  static const String organizeConfirm = 'organize-confirm';
  static const String organizePlan = 'organize-plan';
  static const String organizePreview = 'organize-preview';
  static const String organizeProfile = 'organize-profile';
  static const String organizeReport = 'organize-report';

  // player: Playback surfaces: transport, stars and ratings, chapters, sleep timer, transcript.
  static const String addToPlaylist = 'add-to-playlist';
  static const String downloadButton = 'download-button';
  static const String instantMix = 'instant-mix';
  static String playerChapter(Object index) => 'player-chapter-$index';
  static const String playerChapters = 'player-chapters';
  static const String playerDevices = 'player-devices';
  static const String playerDiscover = 'player-discover';
  static const String playerSeek = 'player-seek';
  static const String playerSpeed = 'player-speed';
  static const String playerToggle = 'player-toggle';
  static const String playerTrim = 'player-trim';
  static String rating(Object scope, Object value) => '${scope}rating-$value';
  static const String shareLink = 'share-link';
  static const String similarTracks = 'similar-tracks';
  static String sleepTimer(Object minutes) => 'sleep-timer-$minutes';
  static const String sleepTimerCancel = 'sleep-timer-cancel';
  static const String sleepTimerChapter = 'sleep-timer-chapter';
  static const String sleepTimerCustomField = 'sleep-timer-custom-field';
  static const String sleepTimerCustomStart = 'sleep-timer-custom-start';
  static const String sleepTimerOpen = 'sleep-timer-open';
  static String starButton(Object scope) => '${scope}star-button';

  // playlists: Playlists, their entries, and the smart-rule editor.
  static const String m3uImportConfirm = 'm3u-import-confirm';
  static String playlist(Object pid) => 'playlist-$pid';
  static const String playlistAdd = 'playlist-add';
  static const String playlistCreateConfirm = 'playlist-create-confirm';
  static const String playlistEditRule = 'playlist-edit-rule';
  static String playlistEntry(Object index) => 'playlist-entry-$index';
  static String playlistEntryRemove(Object index) =>
      'playlist-entry-remove-$index';
  static const String playlistExportPortable = 'playlist-export-portable';
  static const String playlistImport = 'playlist-import';
  static const String playlistImportRun = 'playlist-import-run';
  static const String playlistImportSource = 'playlist-import-source';
  static const String playlistResetCover = 'playlist-reset-cover';
  static const String playlistSetCover = 'playlist-set-cover';
  static const String playlistShareLink = 'playlist-share-link';
  static const String ruleAddCondition = 'rule-add-condition';
  static const String ruleSave = 'rule-save';

  // podcasts: Podcasts: shows, episodes, and subscription actions.
  static String episode(Object pid) => 'episode-$pid';
  static String episodeFetch(Object pid) => 'episode-fetch-$pid';
  static String episodeInfo(Object pid) => 'episode-info-$pid';
  static String episodeRemove(Object pid) => 'episode-remove-$pid';
  static String notesLink(Object index) => 'notes-link-$index';
  static String podcast(Object pid) => 'podcast-$pid';
  static const String podcastAdd = 'podcast-add';
  static const String podcastSettingsOpen = 'podcast-settings-open';
  static const String podcastSettingsRetention = 'podcast-settings-retention';
  static const String podcastSettingsSave = 'podcast-settings-save';
  static const String podcastSettingsSpeed = 'podcast-settings-speed';
  static const String podcastSubscribe = 'podcast-subscribe';
  static const String podcastSubscribeConfirm = 'podcast-subscribe-confirm';
  static const String podcastUnsubscribe = 'podcast-unsubscribe';
  static String transcriptCue(Object index) => 'transcript-cue-$index';
  static const String transcriptOpen = 'transcript-open';
  static const String unsubscribeKeepFiles = 'unsubscribe-keep-files';
  static const String unsubscribeRemoveFiles = 'unsubscribe-remove-files';

  // prototype: The editing prototype kept behind its own route for the e2e keyboard contract.
  static String protoCellArtist(Object index) => 'proto-cell-$index-artist';
  static String protoCellCurrent(Object index) => 'proto-cell-$index-current';
  static String protoEdit(Object index) => 'proto-edit-$index';
  static String protoKebab(Object index) => 'proto-kebab-$index';
  static const String protoMenuApply = 'proto-menu-apply';
  static const String protoMenuCopy = 'proto-menu-copy';
  static String protoRow(Object index) => 'proto-row-$index';
  static const String protoTable = 'proto-table';

  // radio: Internet radio stations.
  static String radio(Object pid) => 'radio-$pid';
  static const String radioAdd = 'radio-add';
  static const String radioAddConfirm = 'radio-add-confirm';

  // review: The review queue and its keyboard-first controls.
  static String candidate(Object mbid) => 'candidate-$mbid';
  static String diffMissing(Object index) => 'diff-missing-$index';
  static String diffRow(Object index) => 'diff-row-$index';
  static String editMetadata(Object pid) => 'edit-metadata-$pid';
  static const String matchingMenu = 'matching-menu';
  static const String reviewApprove = 'review-approve';
  static const String reviewAsIs = 'review-as-is';
  static const String reviewBulkApprove = 'review-bulk-approve';
  static const String reviewBulkAsIs = 'review-bulk-as-is';
  static const String reviewBulkSkip = 'review-bulk-skip';
  static const String reviewDiscard = 'review-discard';
  static String reviewFilter(Object name) => 'review-filter-$name';
  static const String reviewRevert = 'review-revert';
  static String reviewRow(Object id) => 'review-row-$id';
  static const String reviewSelectToggle = 'review-select-toggle';
  static const String reviewSkip = 'review-skip';
  static const String reviewUnofficial = 'review-unofficial';
  static String trackMenu(Object pid) => 'track-menu-$pid';

  // settings: Settings: account, devices, app passwords, notifications, scrobblers, appearance.
  static const String appPasswordAdd = 'app-password-add';
  static String appPasswordRevoke(Object id) => 'app-password-revoke-$id';
  static String deviceRevoke(Object id) => 'device-revoke-$id';
  static String deviceRow(Object id) => 'device-row-$id';
  static const String lastfmCredentialsClear = 'lastfm-credentials-clear';
  static const String lastfmCredentialsSave = 'lastfm-credentials-save';
  static const String listenbrainzConnectConfirm =
      'listenbrainz-connect-confirm';
  static const String logoutButton = 'logout-button';
  static const String notifyServerTargetAdd = 'notify-server-target-add';
  static const String notifyTargetAdd = 'notify-target-add';
  static String notifyTargetTest(Object pid) => 'notify-target-test-$pid';
  static const String openShareLinks = 'open-share-links';
  static String scrobbler(Object service) => 'scrobbler-$service';
  static String scrobblerConnect(Object service) =>
      'scrobbler-connect-$service';
  static String scrobblerDisconnect(Object service) =>
      'scrobbler-disconnect-$service';
  static const String scrobblerSetupLastfm = 'scrobbler-setup-lastfm';
  static const String sharedStatsSwitch = 'shared-stats-switch';
  static const String themeSelect = 'theme-select';
  static const String timezoneEdit = 'timezone-edit';
  static const String timezoneSave = 'timezone-save';

  // shell: The adaptive shell's navigation chrome: tabs, icon rail, sidebar.
  static String navDestination(Object name) => 'nav-$name';
  static String navGroup(Object name) => 'nav-group-$name';
  static const String navOverflow = 'nav-overflow';
  static const String navRegion = 'nav-region';
  static const String navSidebarCollapse = 'nav-sidebar-collapse';

  // sharing: Shares and share links.
  static String shareCopy(Object pid) => 'share-copy-$pid';
  static const String shareCreate = 'share-create';
  static const String shareExpiry = 'share-expiry';
  static String shareRevoke(Object pid) => 'share-revoke-$pid';
  static String shareRow(Object pid) => 'share-row-$pid';

  // stats: Listening stats and year in review.
  static const String listenLogClientFilter = 'listen-log-client-filter';
  static const String openListenLog = 'open-listen-log';
  static const String openYearInReview = 'open-year-in-review';
  static String statsBucket(Object bucket) => 'stats-bucket-$bucket';
  static String statsRange(Object range) => 'stats-range-$range';
  static String top(Object kind) => 'top-kind-$kind';
  static const String yirNextYear = 'yir-next-year';
  static const String yirPersonal = 'yir-personal';
  static const String yirPrevYear = 'yir-prev-year';
  static const String yirServer = 'yir-server';

  // tools: Long-running tools and their progress rows.
  static String taskRow(Object id) => 'task-row-$id';

  // uploads: Uploads: batches, rows, duplicates, and the add-to-library flow.
  static const String acquireFormat = 'acquire-format';
  static const String acquireSubmit = 'acquire-submit';
  static const String addFromUrl = 'add-from-url';
  static const String addUploadFile = 'add-upload-file';
  static const String addUploadFolder = 'add-upload-folder';
  static String uploadBatch(Object batchId) => 'upload-batch-$batchId';
  static String uploadDelete(Object id) => 'upload-delete-$id';
  static const String uploadDropTarget = 'upload-drop-target';
  static String uploadDuplicate(Object id) => 'upload-duplicate-$id';
  static const String uploadFromUrl = 'upload-from-url';
  static const String uploadGrouping = 'upload-grouping';
  static String uploadGroupingOption(Object wireName) =>
      'upload-grouping-$wireName';
  static const String uploadMediaConfirm = 'upload-media-confirm';
  static const String uploadMediaType = 'upload-media-type';
  static const String uploadPick = 'upload-pick';
  static const String uploadQuota = 'upload-quota';
  static String uploadRetry(Object id) => 'upload-retry-$id';
  static String uploadReview(Object id) => 'upload-review-$id';
  static String uploadRow(Object id) => 'upload-row-$id';
}
