// GENERATED by `make generate` from app/semantics-ids/. Do not edit.
//
// The semantics identifiers this app exposes. Every
// `Semantics(identifier:)` in the client reads from here, and
// the e2e suite compiles against the same list in
// e2e/tests/semantics-ids.ts, so the two cannot drift.

/// Stable identifiers for the controls the e2e suite drives.
abstract final class SemanticsIds {
  // admin: The admin console: its shell and dashboard, libraries, genres, users, settings, schedules, backups, trash, audit, migration.
  static String adminAction(Object name) => 'admin-action-$name';
  static const String adminAudit = 'admin-audit';
  static const String adminNotifications = 'admin-notifications';
  static const String adminBackups = 'admin-backups';
  static const String adminConsole = 'admin-console';
  static const String adminDashboard = 'admin-dashboard';
  static const String adminForbidden = 'admin-forbidden';
  static const String adminGenres = 'admin-genres';
  static const String adminLibraries = 'admin-libraries';
  static const String adminMigrate = 'admin-migrate';
  static const String adminSchedules = 'admin-schedules';
  static String adminSection(Object name) => 'admin-section-$name';
  static const String adminSettingsSection = 'admin-settings-section';
  static const String adminShares = 'admin-shares';
  static const String adminSharesEmpty = 'admin-shares-empty';
  static String adminTile(Object name) => 'admin-tile-$name';
  static const String adminTrash = 'admin-trash';
  static const String adminUsers = 'admin-users';
  static const String adminWizard = 'admin-wizard';
  static const String adminWizardSkip = 'admin-wizard-skip';
  static String adminWizardStep(Object name) => 'admin-wizard-step-$name';
  static const String auditFilter = 'audit-filter';
  static const String auditFilterClear = 'audit-filter-clear';
  static String auditRow(Object id) => 'audit-row-$id';
  static const String backupCreate = 'backup-create';
  static const String backupImport = 'backup-import';
  static String backupMenu(Object id) => 'backup-menu-$id';
  static String backupMenuAction(Object action, Object id) =>
      'backup-$action-$id';
  static String backupRow(Object id) => 'backup-row-$id';
  static const String confirmAccept = 'confirm-accept';
  static const String confirmCancel = 'confirm-cancel';
  static const String confirmField = 'confirm-field';
  static const String genreAdd = 'genre-add';
  static const String genreAliases = 'genre-aliases';
  static const String genreDelete = 'genre-delete';
  static const String genreName = 'genre-name';
  static String genreNode(Object name) => 'genre-node-$name';
  static const String genreNormalize = 'genre-normalize';
  static const String genreNormalizeDryRun = 'genre-normalize-dry-run';
  static const String genreParent = 'genre-parent';
  static const String genreRevert = 'genre-revert';
  static const String genreSave = 'genre-save';
  static const String inviteCreate = 'invite-create';
  static String inviteRevoke(Object id) => 'invite-revoke-$id';
  static String inviteRow(Object id) => 'invite-row-$id';
  static const String inviteToken = 'invite-token';
  static String libraryDetail(Object id) => 'library-detail-$id';
  static const String libraryManaged = 'library-managed';
  static String libraryMatching(Object id) => 'library-matching-$id';
  static const String libraryMedia = 'library-media';
  static const String libraryName = 'library-name';
  static const String libraryPath = 'library-path';
  static String libraryReadOnly(Object id) => 'library-read-only-$id';
  static String libraryRescan(Object id) => 'library-rescan-$id';
  static const String libraryRescanConfirm = 'library-rescan-confirm';
  static const String libraryRescanForce = 'library-rescan-force';
  static String libraryRow(Object id) => 'library-row-$id';
  static const String librarySubmit = 'library-submit';
  static const String libraryWarning = 'library-warning';
  static const String migratePassword = 'migrate-password';
  static const String migrateServerUrl = 'migrate-server-url';
  static const String migrateSource = 'migrate-source';
  static const String migrateSubmit = 'migrate-submit';
  static const String migrateToken = 'migrate-token';
  static const String migrateUsername = 'migrate-username';
  static const String permDelete = 'perm-delete';
  static const String permDownload = 'perm-download';
  static const String permExplicit = 'perm-explicit';
  static const String permManagePodcasts = 'perm-manage-podcasts';
  static const String permMaxKbps = 'perm-max-kbps';
  static const String permSharedOutputs = 'perm-shared-outputs';
  static String requestApprove(Object id) => 'request-approve-$id';
  static String requestReject(Object id) => 'request-reject-$id';
  static String requestRow(Object id) => 'request-row-$id';
  static const String restoreBanner = 'restore-banner';
  static const String restoreCancel = 'restore-cancel';
  static String scheduleCron(Object kind) => 'schedule-cron-$kind';
  static String scheduleEnabled(Object kind) => 'schedule-enabled-$kind';
  static String scheduleRow(Object kind) => 'schedule-row-$kind';
  static String scheduleSave(Object kind) => 'schedule-save-$kind';
  static const String settingReadOnly = 'setting-read-only';
  static const String settingSignupEnabled = 'setting-signup-enabled';
  static const String settingRadioExternalArt = 'setting-radio-external-art';
  static const String settingSonicAnalysis = 'setting-sonic-analysis';
  static const String signupRequests = 'signup-requests';
  static String tagRule(Object list, Object index) => '$list-rule-$index';
  static String tagRuleAdd(Object list) => '$list-add';
  static String tagRuleKey(Object list) => '$list-key';
  static String tagRuleValue(Object list) => '$list-value';
  static const String thumbsCard = 'thumbs-card';
  static const String thumbsClear = 'thumbs-clear';
  static const String thumbsClearConfirm = 'thumbs-clear-confirm';
  static const String transcodingActivity = 'transcoding-activity';
  static const String transcodingActivityRefresh =
      'transcoding-activity-refresh';
  static const String transcodingDefaultKbps = 'transcoding-default-kbps';
  static const String transcodingMaxConcurrent = 'transcoding-max-concurrent';
  static const String transcodingMaxPerUser = 'transcoding-max-per-user';
  static const String transcodingSave = 'transcoding-save';
  static String trashDetail(Object id) => 'trash-detail-$id';
  static const String trashEmpty = 'trash-empty';
  static const String trashIncludeRestored = 'trash-include-restored';
  static String trashPurge(Object id) => 'trash-purge-$id';
  static const String trashPurgeConfirm = 'trash-purge-confirm';
  static String trashRestore(Object id) => 'trash-restore-$id';
  static const String taskRetentionDays = 'task-retention-days';
  static const String trashRetentionDays = 'trash-retention-days';
  static const String trashRetentionSave = 'trash-retention-save';
  static String trashRow(Object id) => 'trash-row-$id';
  static const String userAccessAll = 'user-access-all';
  static const String userAdminRole = 'user-admin-role';
  static const String userChildPreset = 'user-child-preset';
  static const String userDelete = 'user-delete';
  static String userDetail(Object id) => 'user-detail-$id';
  static const String userDisabled = 'user-disabled';
  static String userLibrary(Object id) => 'user-library-$id';
  static const String userQuota = 'user-quota';
  static const String userRevokeSessions = 'user-revoke-sessions';
  static String userRow(Object id) => 'user-row-$id';
  static const String userSave = 'user-save';
  static const String userSetPassword = 'user-set-password';
  static const String userUploadEnabled = 'user-upload-enabled';

  // auth: Sign-in, first-run setup, signup, and the pre-login server-address screen. The names here are frozen vocabulary for the accessibility audit.
  static const String connectServerAddress = 'connect-server-address';
  static const String connectServerError = 'connect-server-error';
  static const String connectServerOpen = 'connect-server-open';
  static const String connectServerSubmit = 'connect-server-submit';
  static const String loginError = 'login-error';
  static const String loginPassword = 'login-password';
  static const String loginSubmit = 'login-submit';
  static const String loginUsername = 'login-username';
  static String oidcLogin(Object id) => 'oidc-login-$id';
  static const String setupConfirm = 'setup-confirm';
  static const String setupDisplayName = 'setup-display-name';
  static const String setupError = 'setup-error';
  static const String setupPassword = 'setup-password';
  static const String setupSubmit = 'setup-submit';
  static const String setupUsername = 'setup-username';
  static const String signupError = 'signup-error';
  static const String signupInviteToken = 'signup-invite-token';
  static const String signupOpen = 'signup-open';
  static const String signupPassword = 'signup-password';
  static const String signupResult = 'signup-result';
  static const String signupSubmit = 'signup-submit';
  static const String signupUsername = 'signup-username';

  // books: Audiobooks: the hub, the book screen, its chapters, and its per-book settings.
  static String book(Object pid) => 'book-$pid';
  static String bookAuthorFilter(Object key) => 'book-author-$key';
  static const String bookChapterEditor = 'book-chapter-editor';
  static const String bookChapterEditorAdd = 'book-chapter-editor-add';
  static String bookChapterEditorRemove(Object index) =>
      'book-chapter-editor-remove-$index';
  static const String bookChapterEditorRestore = 'book-chapter-editor-restore';
  static String bookChapterEditorStart(Object index) =>
      'book-chapter-editor-start-$index';
  static String bookChapterEditorTitle(Object index) =>
      'book-chapter-editor-title-$index';
  static String bookContinue(Object pid) => 'book-continue-$pid';
  static const String bookDownload = 'book-download';
  static const String bookEdition = 'book-edition';
  static String bookFinishedFilter(Object name) => 'book-finished-$name';
  static const String bookMarkFinished = 'book-mark-finished';
  static const String bookOverflow = 'book-overflow';
  static const String bookPartsNote = 'book-parts-note';
  static const String bookPin = 'book-pin';
  static const String bookResume = 'book-resume';
  static const String bookSettingsOpen = 'book-settings-open';
  static const String bookSettingsSave = 'book-settings-save';
  static const String bookSettingsSpeed = 'book-settings-speed';
  static String bookSort(Object name) => 'book-sort-$name';
  static const String bookStartOver = 'book-start-over';
  static const String booksAdd = 'books-add';
  static const String booksHub = 'books-hub';
  static const String booksHubOverflow = 'books-hub-overflow';
  static String chapter(Object index) => 'chapter-$index';
  static const String seriesMerge = 'series-merge';
  static const String seriesMergeSheet = 'series-merge-sheet';
  static String seriesMergeTarget(Object pid) => 'series-merge-target-$pid';

  // commands: The command palette, the keyboard reference sheet, and the rows in each.
  static const String commandPalette = 'command-palette';
  static String commandPaletteEntry(Object id) => 'command-palette-entry-$id';
  static const String commandPaletteField = 'command-palette-field';
  static const String shortcutSheet = 'shortcut-sheet';
  static const String shortcutSheetClose = 'shortcut-sheet-close';
  static String shortcutSheetRow(Object id) => 'shortcut-sheet-row-$id';

  // connect: Connect: the device picker, the disconnect triad, cast preflight, remote sessions, and cast controls.
  static String endpoint(Object id) => 'endpoint-$id';
  static const String picker = 'device-picker';
  static const String pickerCheck = 'device-picker-check';
  static const String pickerOverflow = 'device-picker-overflow';
  static const String pickerThisDevice = 'device-picker-this-device';
  static const String preflight = 'cast-preflight';
  static String preflightBase(Object index) => 'cast-preflight-base-$index';
  static String preflightDevice(Object id) => 'cast-preflight-device-$id';
  static String preflightDeviceBase(Object index) =>
      'cast-preflight-device-base-$index';
  static const String preflightDevices = 'cast-preflight-devices';
  static const String preflightRetry = 'cast-preflight-retry';
  static const String remoteLeave = 'remote-leave';
  static const String remoteNext = 'remote-next';
  static const String remotePlayHere = 'remote-play-here';
  static const String remotePrevious = 'remote-previous';
  static const String remoteSeek = 'remote-seek';
  static const String remoteStopThere = 'remote-stop-there';
  static const String remoteToggle = 'remote-toggle';
  static const String remoteVolume = 'remote-volume';
  static String session(Object id) => 'session-$id';

  // deck: The deck bar, the side panel it opens, and the shell's lifecycle banners.
  static const String bannerReconnecting = 'banner-reconnecting';
  static const String bannerUpdated = 'banner-updated';
  static const String bannerUpdatedReload = 'banner-updated-reload';
  static const String deckBar = 'deck-bar';
  static const String deckCast = 'deck-cast';
  static const String deckExpand = 'deck-expand';
  static const String deckLyrics = 'deck-lyrics';
  static const String deckMore = 'deck-more';
  static const String deckMute = 'deck-mute';
  static const String deckNext = 'deck-next';
  static const String deckOffer = 'deck-offer';
  static const String deckOfferDismiss = 'deck-offer-dismiss';
  static const String deckOfferResume = 'deck-offer-resume';
  static const String deckPlay = 'deck-play';
  static const String deckPrevious = 'deck-previous';
  static const String deckQueue = 'deck-queue';
  static const String deckRepeat = 'deck-repeat';
  static const String deckSeek = 'deck-seek';
  static const String deckShuffle = 'deck-shuffle';
  static const String deckSkipBack = 'deck-skip-back';
  static const String deckSkipForward = 'deck-skip-forward';
  static const String deckSaveSong = 'deck-save-song';
  static const String deckStar = 'deck-star';
  static const String deckVolume = 'deck-volume';
  static const String panel = 'panel';
  static const String panelClose = 'panel-close';
  static const String queueClear = 'queue-clear';
  static String queueEntry(Object queueId) => 'queue-entry-$queueId';
  static String queueEntryDrag(Object id) => 'queue-entry-drag-$id';
  static String queueEntryMore(Object queueId) => 'queue-entry-more-$queueId';
  static String queueEntryRemove(Object queueId) =>
      'queue-entry-remove-$queueId';
  static const String queueHistory = 'queue-history';
  static String queueHistoryEntry(Object id) => 'queue-history-$id';
  static const String queueKeepPlaying = 'queue-keep-playing';
  static const String queueOpen = 'queue-open';
  static String queueEntrySelect(Object queueId) =>
      'queue-entry-select-$queueId';
  static const String queueRepeat = 'queue-repeat';
  static String queueRestoreSession(Object id) => 'queue-restore-session-$id';
  static const String queueScreen = 'queue-screen';
  static const String queueSelectionBottom = 'queue-selection-bottom';
  static const String queueSelectionClear = 'queue-selection-clear';
  static const String queueSelectionRemove = 'queue-selection-remove';
  static const String queueSelectionTop = 'queue-selection-top';
  static const String queueShuffle = 'queue-shuffle';

  // desktop: The desktop shell surfaces: the mini player window and the deck bar's way into it. The tray has no semantics tree of its own.
  static const String deckMiniWindow = 'deck-mini-window';
  static const String miniWindow = 'mini-window';
  static const String miniWindowNext = 'mini-window-next';
  static const String miniWindowPlay = 'mini-window-play';
  static const String miniWindowPrevious = 'mini-window-previous';
  static const String miniWindowRestore = 'mini-window-restore';

  // discovery: Instant mixes, similar tracks, and the track lists they open.
  static const String instantMixRun = 'instant-mix-run';
  static const String mixAdventurousness = 'mix-adventurousness';
  static String mixBasis(Object scope) => '$scope-basis';
  static String scopedItem(Object scope, Object index) => '$scope-item-$index';

  // downloads: The downloads manager: what this device holds and the transfers in flight.
  static String downloadCancel(Object pid) => 'download-cancel-$pid';
  static String downloadPause(Object pid) => 'download-pause-$pid';
  static String downloadRemove(Object pid) => 'download-remove-$pid';
  static String downloadResume(Object pid) => 'download-resume-$pid';
  static String downloadRow(Object pid) => 'download-row-$pid';
  static const String downloadsClearAll = 'downloads-clear-all';
  static const String downloadsOverflow = 'downloads-overflow';
  static const String downloadsRefresh = 'downloads-refresh';
  static const String downloadsRemoveFinished = 'downloads-remove-finished';
  static const String downloadsScreen = 'downloads-screen';
  static const String downloadsStorage = 'downloads-storage';

  // health: Library health: rules, issues, and their fixes.
  static const String adminDiagnostics = 'admin-diagnostics';
  static const String adminHealth = 'admin-health';
  static const String adminHealthRule = 'admin-health-rule';
  static String diagnosticCode(Object code) => 'diagnostic-code-$code';
  static String diagnosticDetail(Object path) => 'diagnostic-detail-$path';
  static String diagnosticRow(Object path) => 'diagnostic-row-$path';
  static const String diagnosticsMore = 'diagnostics-more';
  static String duplicateDetail(Object pid) => 'duplicate-detail-$pid';
  static String duplicateGroup(Object pid) => 'duplicate-group-$pid';
  static String duplicateMerge(Object pid) => 'duplicate-merge-$pid';
  static String health(Object rule) => 'health-rule-$rule';
  static String healthFix(Object rule) => 'health-fix-$rule';
  static String healthIssue(Object pid) => 'health-issue-$pid';
  static const String healthScore = 'health-score';
  static const String healthSweep = 'health-sweep';
  static const String healthWarmingUp = 'health-warming-up';
  static String upgradeDetail(Object itemPid) => 'upgrade-detail-$itemPid';
  static String upgradeGroup(Object itemPid) => 'upgrade-group-$itemPid';
  static String upgradeResolve(Object itemPid) => 'upgrade-resolve-$itemPid';

  // home: Home and the shelf component it shares with the music hub, plus the notifications bell, its full-page screen, and the account control in the top app bar.
  static const String homeAdd = 'home-add';
  static const String homeEpisodeInfo = 'home-episode-info';
  static const String homeEpisodePlay = 'home-episode-play';
  static String homeMix(Object index) => 'home-mix-$index';
  static const String homeReviewPending = 'home-review-pending';
  static const String homeReviewPendingOpen = 'home-review-pending-open';
  static const String homeScreen = 'home-screen';
  static String notificationDelete(Object id) => 'notification-delete-$id';
  static String notificationRow(Object kind, Object target) =>
      'notification-row-$kind-$target';
  static String notificationRowPlain(Object kind) =>
      'notification-row-$kind-none';
  static const String notificationsBell = 'notifications-bell';
  static const String notificationsClear = 'notifications-clear';
  static const String notificationsClearConfirm = 'notifications-clear-confirm';
  static const String notificationsEmpty = 'notifications-empty';
  static const String notificationsMarkAllRead = 'notifications-mark-all-read';
  static const String notificationsPeekRead = 'notifications-peek-read';
  static const String notificationsScreen = 'notifications-screen';
  static String pinSheetTarget(Object pid) => 'pin-sheet-target-$pid';
  static String shelf(Object shelf) => 'shelf-$shelf';
  static String shelfAll(Object shelf) => 'shelf-$shelf-all';
  static String shelfBack(Object shelf) => 'shelf-$shelf-back';
  static String shelfCard(Object shelf, Object pid) => 'shelf-$shelf-$pid';
  static String shelfForward(Object shelf) => 'shelf-$shelf-forward';

  // library: The complete item listings and the per-item rows the sync specs drive.
  static String item(Object pid) => 'item-$pid';
  static const String itemDelete = 'item-delete';
  static const String itemDeleteConfirm = 'item-delete-confirm';
  static String itemDeleteMode(Object mode) => 'item-delete-mode-$mode';
  static const String itemFactsError = 'item-facts-error';
  static String itemFactsRow(Object key) => 'item-facts-$key';
  static String itemFactsSheet(Object pid) => 'item-facts-sheet-$pid';
  static const String itemMenuDetach = 'item-menu-detach';
  static const String itemMenuDetachConfirm = 'item-menu-detach-confirm';
  static const String itemMenuDetachWriteBack = 'item-menu-detach-writeback';
  static const String itemMenuDetails = 'item-menu-details';
  static const String itemMenuGoAlbum = 'item-menu-go-album';
  static const String itemMenuGoArtist = 'item-menu-go-artist';
  static const String itemMenuMix = 'item-menu-mix';
  static const String itemMenuShare = 'item-menu-share-album';
  static const String itemMenuShareItem = 'item-menu-share';
  static String itemMenuSheet(Object pid) => 'item-menu-sheet-$pid';
  static const String offlineBanner = 'offline-banner';

  // metadata: The metadata editor: fields, locks, candidates, and artwork.
  static const String albumEditDetails = 'album-edit-details';
  static const String albumEditReleaseGroup = 'album-edit-release-group';
  static const String albumEditor = 'album-editor';
  static const String albumEditorNames = 'album-editor-names';
  static const String albumEditorTotalTracks = 'album-editor-total-tracks';
  static const String albumEditorTracks = 'album-editor-tracks';
  static const String albumIdentity = 'album-identity';
  static const String albumRewrite = 'album-rewrite';
  static const String albumRewriteApply = 'album-rewrite-apply';
  static const String albumRewriteConfirm = 'album-rewrite-confirm';
  static String albumRewriteField(Object name) => 'album-rewrite-field-$name';
  static const String albumRewriteWriteBack = 'album-rewrite-writeback';
  static const String artLock = 'art-lock';
  static String artLockRole(Object role) => 'art-lock-$role';
  static String artSlot(Object role) => 'art-slot-$role';
  static String artSlotClear(Object role) => 'art-slot-clear-$role';
  static String artSlotDrop(Object role) => 'art-slot-drop-$role';
  static String artSlotSet(Object role) => 'art-slot-set-$role';
  static const String creditAdd = 'credit-add';
  static String creditRemove(Object role, Object name) =>
      'credit-remove-$role-$name';
  static const String creditsNames = 'credits-names';
  static const String creditsRole = 'credits-role';
  static const String enrichPreview = 'enrich-preview';
  static const String enrichPreviewApply = 'enrich-preview-apply';
  static const String enrichPreviewCancel = 'enrich-preview-cancel';
  static const String enrichPreviewCover = 'enrich-preview-cover';
  static String enrichPreviewRow(Object name) => 'enrich-preview-row-$name';
  static const String entityEditor = 'entity-editor';
  static const String entityRenameApply = 'entity-rename-apply';
  static const String entityRenameConfirm = 'entity-rename-confirm';
  static String entityRenameField(Object name) => 'entity-rename-field-$name';
  static const String entityRenameWriteBack = 'entity-rename-writeback';
  static String fieldLock(Object name) => 'field-lock-$name';
  static const String lyricsField = 'lyrics-field';
  static const String lyricsPreview = 'lyrics-preview';
  static const String metadataEditor = 'metadata-editor';
  static const String metadataEnrich = 'metadata-enrich';
  static String metadataField(Object name) => 'metadata-field-$name';
  static const String metadataForbidden = 'metadata-forbidden';
  static const String metadataForce = 'metadata-force';
  static const String metadataGenreAdd = 'metadata-genre-add';
  static String metadataGenreOption(Object name) =>
      'metadata-genre-option-$name';
  static const String metadataGenrePicker = 'metadata-genre-picker';
  static const String metadataGenrePickerApply = 'metadata-genre-picker-apply';
  static const String metadataGenrePickerCustom =
      'metadata-genre-picker-custom';
  static const String metadataGenrePickerSearch =
      'metadata-genre-picker-search';
  static String metadataGenreRemove(Object name) =>
      'metadata-genre-remove-$name';
  static const String metadataLock = 'metadata-lock';
  static const String metadataOpenAlbum = 'metadata-open-album';
  static const String metadataOpenArtist = 'metadata-open-artist';
  static const String metadataOpenReleaseGroup = 'metadata-open-release-group';
  static const String metadataOpenReview = 'metadata-open-review';
  static const String metadataRematch = 'metadata-rematch';
  static const String metadataSave = 'metadata-save';
  static const String metadataSaveBar = 'metadata-save-bar';
  static const String metadataWorkbench = 'metadata-workbench';
  static const String metadataWriteback = 'metadata-writeback';
  static const String metadataWritebackWarning = 'metadata-writeback-warning';
  static const String originCancel = 'origin-cancel';
  static const String originClear = 'origin-clear';
  static const String originEdit = 'origin-edit';
  static const String originId = 'origin-id';
  static const String originProvider = 'origin-provider';
  static const String originSave = 'origin-save';
  static const String originSheet = 'origin-sheet';
  static const String originSourceType = 'origin-source-type';
  static const String originUrl = 'origin-url';
  static const String originWriteBack = 'origin-writeback';
  static const String tagAdd = 'tag-add';
  static const String tagKey = 'tag-key';
  static String tagRemove(Object key) => 'tag-remove-$key';
  static String tagRestore(Object key) => 'tag-restore-$key';
  static const String tagValues = 'tag-values';
  static const String unofficialSwitch = 'unofficial-switch';
  static const String workbenchAlbumRow = 'workbench-album-row';
  static const String workbenchBulkBar = 'workbench-bulk-bar';
  static const String workbenchBulkEdit = 'workbench-bulk-edit';
  static String workbenchBulkField(Object name) => 'workbench-bulk-field-$name';
  static const String workbenchBulkLockedPolicy =
      'workbench-bulk-locked-policy';
  static const String workbenchBulkPane = 'workbench-bulk-pane';
  static const String workbenchBulkSave = 'workbench-bulk-save';
  static const String workbenchDiscardConfirm = 'workbench-discard-confirm';
  static const String workbenchList = 'workbench-list';
  static const String workbenchPane = 'workbench-pane';
  static String workbenchRow(Object pid) => 'workbench-row-$pid';
  static const String workbenchSelectToggle = 'workbench-select-toggle';
  static const String workbenchSplitter = 'workbench-splitter';

  // music: The music hub, its indexes, and the buckets they drill.
  static String albumTrackMore(Object index) => 'album-track-more-$index';
  static String albumTrackPlays(Object index) => 'album-track-plays-$index';
  static String entityAlbum(Object pid) => 'entity-album-$pid';
  static const String entityAllTracks = 'entity-all-tracks';
  static const String entityEditMetadata = 'entity-edit-metadata';
  static const String entityInstantMix = 'entity-instant-mix';
  static const String entityOverflow = 'entity-overflow';
  static const String entityPin = 'entity-pin';
  static const String entityPlay = 'entity-play';
  static const String entityShare = 'entity-share';
  static const String entityShuffle = 'entity-shuffle';
  static String indexBucket(Object index) => 'index-bucket-$index';
  static String indexBucketMore(Object index) => 'index-bucket-more-$index';
  static const String indexCount = 'index-count';
  static String indexItem(Object index) => 'index-item-$index';
  static const String indexRail = 'index-rail';
  static String indexRailLetter(Object letter) => 'index-rail-$letter';
  static const String indexRailStart = 'index-rail-start';
  static const String indexSort = 'index-sort';
  static const String indexSortCount = 'index-sort-count';
  static String listingRowMore(Object pid) => 'listing-row-more-$pid';
  static const String listingShuffle = 'listing-shuffle';
  static const String musicAdd = 'music-add';
  static String musicTile(Object name) => 'music-tile-$name';

  // organize: Organize: previews, duplicates, and upgrade groups.
  static const String adminOrganize = 'admin-organize';
  static const String organizeApply = 'organize-apply';
  static const String organizeConfirm = 'organize-confirm';
  static const String organizePlan = 'organize-plan';
  static const String organizePreview = 'organize-preview';
  static const String organizeProfile = 'organize-profile';
  static const String organizeReport = 'organize-report';
  static String organizeRow(Object from) => 'organize-row-$from';
  static String organizeRowDetail(Object from) => 'organize-row-detail-$from';

  // player: Playback surfaces: transport, stars and ratings, speed, chapters, bookmarks, sleep timer, notes and transcript, lyrics, the visualizer, and car mode.
  static const String addToPlaylist = 'add-to-playlist';
  static const String carExit = 'car-exit';
  static const String carNext = 'car-next';
  static const String carPrevious = 'car-previous';
  static const String carSurface = 'car-surface';
  static const String carToggle = 'car-toggle';
  static const String downloadButton = 'download-button';
  static const String instantMix = 'instant-mix';
  static const String lyricsAdd = 'lyrics-add';
  static const String lyricsFollow = 'lyrics-follow';
  static String lyricsLine(Object index) => 'lyrics-line-$index';
  static const String lyricsSurface = 'lyrics-surface';
  static const String playerBack = 'player-back';
  static String playerBookmark(Object index) => 'player-bookmark-$index';
  static const String playerBookmarkAdd = 'player-bookmark-add';
  static String playerBookmarkDelete(Object index) =>
      'player-bookmark-delete-$index';
  static const String playerBookmarkNote = 'player-bookmark-note';
  static const String playerBookmarkSheet = 'player-bookmark-sheet';
  static const String playerBookmarks = 'player-bookmarks';
  static const String playerCarMode = 'player-car-mode';
  static String playerChapter(Object index) => 'player-chapter-$index';
  static const String playerChapters = 'player-chapters';
  static const String playerDevices = 'player-devices';
  static const String playerDiscover = 'player-discover';
  static const String playerFindInLibrary = 'player-find-in-library';
  static const String playerFunding = 'player-funding';
  static const String playerGoToShow = 'player-go-to-show';
  static const String playerLyrics = 'player-lyrics';
  static const String playerMarkPlayed = 'player-mark-played';
  static const String playerMore = 'player-more';
  static const String playerMute = 'player-mute';
  static const String playerNext = 'player-next';
  static const String playerPrevious = 'player-previous';
  static const String playerQueue = 'player-queue';
  static String playerRegion(Object name) => 'player-region-$name';
  static const String playerRepeat = 'player-repeat';
  static const String playerRetry = 'player-retry';
  static const String playerSaveSong = 'player-save-song';
  static const String playerSeek = 'player-seek';
  static const String playerShow = 'player-show';
  static const String playerShuffle = 'player-shuffle';
  static const String playerSkipBack = 'player-skip-back';
  static const String playerSkipForward = 'player-skip-forward';
  static const String playerSpeed = 'player-speed';
  static const String playerSpeedFaster = 'player-speed-faster';
  static String playerSpeedPreset(Object percent) => 'player-speed-$percent';
  static const String playerSpeedSheet = 'player-speed-sheet';
  static const String playerSpeedSlower = 'player-speed-slower';
  static const String playerStationInfo = 'player-station-info';
  static const String playerSurface = 'player-surface';
  static String playerTimeline(Object name) => 'player-timeline-$name';
  static const String playerToggle = 'player-toggle';
  static const String playerTrim = 'player-trim';
  static const String playerUpNext = 'player-up-next';
  static const String playerVisualizer = 'player-visualizer';
  static const String playerVoiceBoost = 'player-voice-boost';
  static const String playerVolume = 'player-volume';
  static String rating(Object scope, Object value) => '${scope}rating-$value';
  static const String shareLink = 'share-link';
  static const String similarTracks = 'similar-tracks';
  static String sleepTimer(Object minutes) => 'sleep-timer-$minutes';
  static const String sleepTimerCancel = 'sleep-timer-cancel';
  static const String sleepTimerChapter = 'sleep-timer-chapter';
  static const String sleepTimerCustomField = 'sleep-timer-custom-field';
  static const String sleepTimerCustomStart = 'sleep-timer-custom-start';
  static const String sleepTimerExtend = 'sleep-timer-extend';
  static const String sleepTimerOpen = 'sleep-timer-open';
  static String starButton(Object scope) => '${scope}star-button';
  static const String transcriptFollow = 'transcript-follow';
  static const String visualizerClose = 'visualizer-close';
  static String visualizerMode(Object name) => 'visualizer-mode-$name';
  static const String visualizerNext = 'visualizer-next';
  static const String visualizerPrevious = 'visualizer-previous';
  static const String visualizerSeek = 'visualizer-seek';
  static const String visualizerSurface = 'visualizer-surface';
  static const String visualizerToggle = 'visualizer-toggle';

  // playlists: Playlists, their entries, and the smart-rule editor.
  static const String addToPlaylistNew = 'add-to-playlist-new';
  static String addToPlaylistTarget(Object pid) =>
      'add-to-playlist-target-$pid';
  static String playlist(Object pid) => 'playlist-$pid';
  static const String playlistAdd = 'playlist-add';
  static const String playlistAddField = 'playlist-add-field';
  static String playlistAddResult(Object index) => 'playlist-add-result-$index';
  static const String playlistConflict = 'playlist-conflict';
  static const String playlistCreateConfirm = 'playlist-create-confirm';
  static String playlistCreateKind(Object kind) => 'playlist-create-kind-$kind';
  static const String playlistCreateShared = 'playlist-create-shared';
  static const String playlistDelete = 'playlist-delete';
  static const String playlistDeleteConfirm = 'playlist-delete-confirm';
  static const String playlistEditRule = 'playlist-edit-rule';
  static String playlistEntry(Object index) => 'playlist-entry-$index';
  static String playlistEntryDrag(Object index) => 'playlist-entry-drag-$index';
  static String playlistEntryMore(Object index) => 'playlist-entry-more-$index';
  static String playlistEntryRemove(Object index) =>
      'playlist-entry-remove-$index';
  static const String playlistExportCopy = 'playlist-export-copy';
  static const String playlistExportM3u = 'playlist-export-m3u';
  static const String playlistExportNsp = 'playlist-export-nsp';
  static const String playlistExportNspLoss = 'playlist-export-nsp-loss';
  static String playlistExportNspLossRow(Object index) =>
      'playlist-export-nsp-loss-$index';
  static const String playlistExportNspProceed = 'playlist-export-nsp-proceed';
  static const String playlistExportPortable = 'playlist-export-portable';
  static const String playlistImport = 'playlist-import';
  static const String playlistImportKeepMatched =
      'playlist-import-keep-matched';
  static const String playlistImportName = 'playlist-import-name';
  static const String playlistImportPayload = 'playlist-import-payload';
  static const String playlistImportReport = 'playlist-import-report';
  static const String playlistImportRun = 'playlist-import-run';
  static String playlistImportSource(Object source) =>
      'playlist-import-source-$source';
  static const String playlistNameField = 'playlist-name-field';
  static const String playlistOverflow = 'playlist-overflow';
  static const String playlistPin = 'playlist-pin';
  static const String playlistRename = 'playlist-rename';
  static const String playlistResetCover = 'playlist-reset-cover';
  static const String playlistRuleSummary = 'playlist-rule-summary';
  static const String playlistSetCover = 'playlist-set-cover';
  static const String playlistShareLink = 'playlist-share-link';
  static const String playlistSyncChip = 'playlist-sync-chip';
  static const String playlistSyncInterval = 'playlist-sync-interval';
  static String playlistSyncIntervalOption(Object hours) =>
      'playlist-sync-interval-$hours';
  static const String playlistSyncMode = 'playlist-sync-mode';
  static String playlistSyncModeOption(Object mode) =>
      'playlist-sync-mode-$mode';
  static const String playlistSyncNow = 'playlist-sync-now';
  static const String playlistSyncPreview = 'playlist-sync-preview';
  static const String playlistSyncPreviewDialog =
      'playlist-sync-preview-dialog';
  static const String playlistSyncSave = 'playlist-sync-save';
  static const String playlistSyncSettings = 'playlist-sync-settings';
  static const String playlistSyncSheet = 'playlist-sync-sheet';
  static const String playlistSyncUnbind = 'playlist-sync-unbind';
  static const String playlistSyncUrl = 'playlist-sync-url';
  static const String playlistVisibility = 'playlist-visibility';
  static const String ruleAddCondition = 'rule-add-condition';
  static const String ruleAddGroup = 'rule-add-group';
  static const String ruleAddSort = 'rule-add-sort';
  static String ruleConditionRemove(Object index) =>
      'rule-condition-remove-$index';
  static String ruleField(Object index) => 'rule-field-$index';
  static String ruleGroupMode(Object index) => 'rule-group-mode-$index';
  static String ruleGroupRemove(Object index) => 'rule-group-remove-$index';
  static const String ruleLimitMode = 'rule-limit-mode';
  static const String ruleLimitSeed = 'rule-limit-seed';
  static const String ruleLimitValue = 'rule-limit-value';
  static String ruleOp(Object index) => 'rule-op-$index';
  static const String rulePreviewTotal = 'rule-preview-total';
  static const String ruleSave = 'rule-save';
  static String ruleSortDirection(Object index) => 'rule-sort-direction-$index';
  static String ruleSortField(Object index) => 'rule-sort-field-$index';
  static String ruleSortRemove(Object index) => 'rule-sort-remove-$index';
  static String ruleValue(Object index) => 'rule-value-$index';
  static String ruleValueHigh(Object index) => 'rule-value-high-$index';

  // podcasts: Podcasts: shows, episodes, and subscription actions.
  static String episode(Object pid) => 'episode-$pid';
  static String episodeContinue(Object pid) => 'episode-continue-$pid';
  static String episodeFetch(Object pid) => 'episode-fetch-$pid';
  static String episodeInfo(Object pid) => 'episode-info-$pid';
  static const String episodeMarkPlayed = 'episode-mark-played';
  static const String episodePlay = 'episode-play';
  static const String episodeQueue = 'episode-queue';
  static String episodeRemove(Object pid) => 'episode-remove-$pid';
  static String episodeSection(Object name) => 'episode-section-$name';
  static String episodeSelect(Object pid) => 'episode-select-$pid';
  static const String episodeShare = 'episode-share';
  static const String markOlderConfirm = 'mark-older-confirm';
  static const String markOlderPlayed = 'mark-older-played';
  static String markOlderPreset(Object name) => 'mark-older-preset-$name';
  static String notesLink(Object index) => 'notes-link-$index';
  static String podcast(Object pid) => 'podcast-$pid';
  static const String podcastAdd = 'podcast-add';
  static const String podcastAddByUrl = 'podcast-add-by-url';
  static String podcastFolder(Object name) => 'podcast-folder-$name';
  static const String podcastOpmlExport = 'podcast-opml-export';
  static const String podcastOpmlImport = 'podcast-opml-import';
  static const String podcastOverflow = 'podcast-overflow';
  static const String podcastSearchField = 'podcast-search-field';
  static const String podcastSearchRun = 'podcast-search-run';
  static String podcastSearchSubscribe(Object index) =>
      'podcast-search-subscribe-$index';
  static const String podcastSettingsExclude = 'podcast-settings-exclude';
  static const String podcastSettingsInclude = 'podcast-settings-include';
  static const String podcastSettingsOpen = 'podcast-settings-open';
  static const String podcastSettingsRetention = 'podcast-settings-retention';
  static const String podcastSettingsSave = 'podcast-settings-save';
  static const String podcastSettingsSpeed = 'podcast-settings-speed';
  static String podcastSort(Object name) => 'podcast-sort-$name';
  static const String podcastSubscribe = 'podcast-subscribe';
  static const String podcastSubscribeConfirm = 'podcast-subscribe-confirm';
  static const String podcastUnsubscribe = 'podcast-unsubscribe';
  static const String selectionClear = 'selection-clear';
  static const String selectionDownload = 'selection-download';
  static const String selectionMarkPlayed = 'selection-mark-played';
  static const String selectionQueue = 'selection-queue';
  static String showEpisodeFilter(Object name) => 'show-episode-filter-$name';
  static const String showEpisodeSearch = 'show-episode-search';
  static const String showOverflow = 'show-overflow';
  static const String showPin = 'show-pin';
  static const String showSetCover = 'show-set-cover';
  static String transcriptCue(Object index) => 'transcript-cue-$index';
  static const String transcriptOpen = 'transcript-open';
  static const String unsubscribeKeepFiles = 'unsubscribe-keep-files';
  static const String unsubscribeRemoveFiles = 'unsubscribe-remove-files';

  // radio: The radio hub: the favorites dial, the station grid, and the add-station flow.
  static String radio(Object pid) => 'radio-$pid';
  static const String radioAdd = 'radio-add';
  static const String radioAddConfirm = 'radio-add-confirm';
  static String radioAddDirectory(Object index) => 'radio-add-directory-$index';
  static String radioDelete(Object pid) => 'radio-delete-$pid';
  static const String radioDial = 'radio-dial';
  static String radioEdit(Object pid) => 'radio-edit-$pid';
  static String radioFavorite(Object pid) => 'radio-favorite-$pid';
  static const String radioHomepageField = 'radio-homepage-field';
  static const String radioHub = 'radio-hub';
  static const String radioLogoField = 'radio-logo-field';
  static String radioMenu(Object pid) => 'radio-menu-$pid';
  static const String radioMoreOptions = 'radio-more-options';
  static const String radioMute = 'radio-mute';
  static const String radioNameField = 'radio-name-field';
  static const String radioNowPlaying = 'radio-now-playing';
  static String radioPinned(Object pid) => 'radio-pinned-$pid';
  static const String radioSaved = 'radio-saved';
  static const String radioSavedAcquire = 'radio-saved-acquire';
  static String radioSavedEntry(Object pid) => 'radio-saved-entry-$pid';
  static String radioSavedFind(Object pid) => 'radio-saved-find-$pid';
  static const String radioSavedIdentify = 'radio-saved-identify';
  static String radioSavedIdentifyEntry(Object id) =>
      'radio-saved-identify-entry-$id';
  static String radioSavedMore(Object pid) => 'radio-saved-more-$pid';
  static const String radioSavedOpen = 'radio-saved-open';
  static String radioSavedRemove(Object pid) => 'radio-saved-remove-$pid';
  static String radioSearchAdd(Object index) => 'radio-search-add-$index';
  static const String radioSearchField = 'radio-search-field';
  static const String radioSearchRun = 'radio-search-run';
  static const String radioTune = 'radio-tune';
  static const String radioUrlField = 'radio-url-field';
  static const String radioVolume = 'radio-volume';

  // review: The review queue and its keyboard-first controls.
  static const String adminReview = 'admin-review';
  static const String adminReviewEntry = 'admin-review-entry';
  static String candidate(Object mbid) => 'candidate-$mbid';
  static String diffMissing(Object index) => 'diff-missing-$index';
  static const String diffMissingBand = 'diff-missing-band';
  static String diffRow(Object index) => 'diff-row-$index';
  static String editMetadata(Object pid) => 'edit-metadata-$pid';
  static const String matchingMenu = 'matching-menu';
  static String matchingOption(Object libraryPid, Object mode) =>
      'matching-$libraryPid-$mode';
  static String matchingSingles(Object libraryPid) =>
      'matching-singles-$libraryPid';
  static const String reviewApprove = 'review-approve';
  static const String reviewAsIs = 'review-as-is';
  static const String reviewBulkApprove = 'review-bulk-approve';
  static const String reviewBulkAsIs = 'review-bulk-as-is';
  static const String reviewBulkSkip = 'review-bulk-skip';
  static const String reviewDiscard = 'review-discard';
  static String reviewFilter(Object name) => 'review-filter-$name';
  static String reviewIdentifyField(Object name) => 'review-identify-$name';
  static const String reviewIdentifyGroup = 'review-identify-group';
  static const String reviewIdentifySkipped = 'review-identify-skipped';
  static const String reviewIdentifySubmit = 'review-identify-submit';
  static const String reviewIdentifyToggle = 'review-identify-toggle';
  static const String reviewOpenUploads = 'review-open-uploads';
  static const String reviewPane = 'review-pane';
  static const String reviewPaneClose = 'review-pane-close';
  static const String reviewRevert = 'review-revert';
  static String reviewRow(Object id) => 'review-row-$id';
  static const String reviewSelectToggle = 'review-select-toggle';
  static const String reviewSkip = 'review-skip';
  static const String reviewSplitter = 'review-splitter';
  static const String reviewUnofficial = 'review-unofficial';
  static String trackMenu(Object pid) => 'track-menu-$pid';

  // search: The search screen, its filters, and the chrome that opens it.
  static const String searchAction = 'search-action';
  static const String searchClear = 'search-clear';
  static const String searchField = 'search-field';
  static String searchFilter(Object name) => 'search-filter-$name';
  static String searchHit(Object kind, Object index) =>
      'search-hit-$kind-$index';
  static String searchHitMore(Object kind, Object index) =>
      'search-hit-more-$kind-$index';
  static String searchRecent(Object index) => 'search-recent-$index';
  static String searchRecentRemove(Object index) =>
      'search-recent-remove-$index';
  static String searchShowAll(Object kind) => 'search-show-all-$kind';
  static const String searchTruncated = 'search-truncated';

  // settings: Settings: the searchable sections, every leaf control, account, devices, app passwords, notifications, scrobblers.
  static const String aboutDefects = 'about-defects';
  static const String aboutLicenses = 'about-licenses';
  static const String aboutOpen = 'about-open';
  static const String aboutRow = 'about';
  static const String appPasswordAdd = 'app-password-add';
  static String appPasswordRevoke(Object id) => 'app-password-revoke-$id';
  static const String defectsClear = 'defects-clear';
  static const String defectsCopy = 'defects-copy';
  static const String defectsScreen = 'defects-screen';
  static String deviceRename(Object id) => 'device-rename-$id';
  static String deviceRevoke(Object id) => 'device-revoke-$id';
  static String deviceRow(Object id) => 'device-row-$id';
  static const String lastfmCredentialsClear = 'lastfm-credentials-clear';
  static const String lastfmCredentialsSave = 'lastfm-credentials-save';
  static const String listenbrainzConnectConfirm =
      'listenbrainz-connect-confirm';
  static const String logoutButton = 'logout-button';
  static const String notifyServerTargetAdd = 'notify-server-target-add';
  static const String notifyTargetAdd = 'notify-target-add';
  static String notifyTargetTest(Object pid) => 'notify-target-test-$pid';
  static const String openShareLinks = 'open-share-links';
  static const String radioScrobbleSwitch = 'radio-scrobble-switch';
  static String scrobbler(Object service) => 'scrobbler-$service';
  static String scrobblerConnect(Object service) =>
      'scrobbler-connect-$service';
  static String scrobblerDisconnect(Object service) =>
      'scrobbler-disconnect-$service';
  static const String scrobblerSetupLastfm = 'scrobbler-setup-lastfm';
  static const String serverSummary = 'server-summary';
  static String setting(Object id) => 'setting-$id';
  static String settingOption(Object id, Object value) =>
      'setting-option-$id-$value';
  static String settingsResult(Object id) => 'settings-result-$id';
  static const String settingsScreen = 'settings-screen';
  static const String settingsSearch = 'settings-search';
  static String settingsSection(Object section) => 'settings-section-$section';
  static const String sharedStatsSwitch = 'shared-stats-switch';
  static const String themeSelect = 'theme-select';
  static const String timezoneEdit = 'timezone-edit';
  static const String timezoneSave = 'timezone-save';

  // sharing: Shares and share links.
  static const String shareAllowDownload = 'share-allow-download';
  static String shareCopy(Object pid) => 'share-copy-$pid';
  static const String shareCreate = 'share-create';
  static const String shareExpiry = 'share-expiry';
  static String shareRevoke(Object pid) => 'share-revoke-$pid';
  static String shareRow(Object pid) => 'share-row-$pid';
  static const String shareStartAt = 'share-start-at';
  static const String sharesEmpty = 'shares-empty';

  // shell: The adaptive shell's navigation chrome: tabs, icon rail, sidebar, the account menu, and the skip link.
  static const String navAccount = 'nav-account';
  static String navAccountAction(Object name) => 'nav-account-$name';
  static String navDestination(Object name) => 'nav-$name';
  static String navDisclose(Object name) => 'nav-disclose-$name';
  static const String navOverflow = 'nav-overflow';
  static const String navRegion = 'nav-region';
  static const String navSidebarCollapse = 'nav-sidebar-collapse';
  static const String skipToContent = 'skip-to-content';

  // stats: Listening stats and year in review.
  static const String listenLogClientFilter = 'listen-log-client-filter';
  static const String openListenLog = 'open-listen-log';
  static const String openYearInReview = 'open-year-in-review';
  static String shareCardExport(Object format) => 'share-card-export-$format';
  static const String shareCardOpen = 'share-card-open';
  static String shareCardPreview(Object format) => 'share-card-preview-$format';
  static const String statsBucket = 'stats-bucket';
  static String statsRange(Object range) => 'stats-range-$range';
  static String top(Object kind) => 'top-kind-$kind';
  static String topEntry(Object index) => 'top-entry-$index';
  static const String yirNextYear = 'yir-next-year';
  static const String yirPersonal = 'yir-personal';
  static const String yirPrevYear = 'yir-prev-year';
  static const String yirServer = 'yir-server';

  // tools: Long-running tools and their progress rows.
  static String taskDismiss(Object id) => 'task-dismiss-$id';
  static String taskRow(Object id) => 'task-row-$id';
  static const String tasksClearFinished = 'tasks-clear-finished';

  // uploads: Uploads: batches, rows, duplicates, and the add-to-library flow.
  static const String acquireFormat = 'acquire-format';
  static const String acquireIdentify = 'acquire-identify';
  static const String acquireSubmit = 'acquire-submit';
  static const String acquireTasks = 'acquire-tasks';
  static const String acquireUrl = 'acquire-url';
  static const String addFromUrl = 'add-from-url';
  static const String addUploadFile = 'add-upload-file';
  static const String addUploadFolder = 'add-upload-folder';
  static const String addUploadSessions = 'add-upload-sessions';
  static String uploadBatch(Object batchId) => 'upload-batch-$batchId';
  static String uploadDelete(Object id) => 'upload-delete-$id';
  static const String uploadDropTarget = 'upload-drop-target';
  static String uploadDuplicate(Object id) => 'upload-duplicate-$id';
  static const String uploadFromUrl = 'upload-from-url';
  static const String uploadGrouping = 'upload-grouping';
  static String uploadGroupingOption(Object wireName) =>
      'upload-grouping-$wireName';
  static const String uploadIdentify = 'upload-identify';
  static const String uploadIdentifyingReview = 'upload-identifying-review';
  static const String uploadLibrary = 'upload-library';
  static String uploadLibraryOption(Object pid) => 'upload-library-$pid';
  static const String uploadMediaConfirm = 'upload-media-confirm';
  static const String uploadMediaType = 'upload-media-type';
  static const String uploadPick = 'upload-pick';
  static const String uploadQuota = 'upload-quota';
  static String uploadRetry(Object id) => 'upload-retry-$id';
  static String uploadReview(Object id) => 'upload-review-$id';
  static String uploadRow(Object id) => 'upload-row-$id';
  static const String uploadsMore = 'uploads-more';
  static const String uploadsScreen = 'uploads-screen';
}
