package service

import (
	"context"
	"database/sql"
	"io"
	"log/slog"
	"path/filepath"
	"testing"
	"time"

	"github.com/colespringer/waxbin"
	"github.com/colespringer/waxdeck/fixtures"

	wdb "github.com/colespringer/waxdeck/server/internal/db"
	"github.com/colespringer/waxdeck/server/internal/supervise"
)

// TestStartupRefreshRepairsStaleSortKeys pins the one thing an upgrade
// needs and nothing else in the process supplies: a catalog whose stored
// sort keys were generated by an older fold has to be rewritten, and no
// scan will do it. A rescan resolves an unchanged file by its match key
// and returns before the INSERT that writes a sort key, so a stale key
// survives every rescan forever. The proof is therefore a planted key, a
// reopen with scanning off, and the key coming back on its own.
func TestStartupRefreshRepairsStaleSortKeys(t *testing.T) {
	t.Parallel()

	libDir := t.TempDir()
	if _, err := fixtures.Generate(libDir,
		genreTrack("folded", "Folded One", "Jazz", 2*time.Second),
	); err != nil {
		t.Fatalf("generating fixtures: %v", err)
	}
	dataDir := t.TempDir()
	log := slog.New(slog.NewTextHandler(io.Discard, nil))

	// Phase 1: scan, and record both the album's pid and the sort key the
	// current fold generates for it -- the value the repair has to restore.
	const username = "admin"
	var albumPID, want string
	func() {
		ctx, cancel := context.WithCancel(context.Background())
		store, err := wdb.Open(ctx, filepath.Join(dataDir, "waxdeck.db"))
		if err != nil {
			cancel()
			t.Fatal(err)
		}
		group := supervise.NewGroup(log)
		svc, err := Open(ctx, Config{
			DataDir: dataDir,
			Roots:   []Root{{Name: "lib", Path: libDir}},
			Logger:  log,
		}, store, group)
		if err != nil {
			cancel()
			store.Close()
			t.Fatal(err)
		}
		// Wait before Close, and Close before the raw open below: on Windows
		// the catalog file stays locked until the workers are reaped.
		defer func() {
			cancel()
			group.Wait()
			svc.Close()
			store.Close()
		}()

		if _, err := svc.lib.Scan(ctx, waxbin.ScanRequest{}); err != nil {
			t.Fatalf("scanning fixture library: %v", err)
		}
		acct, err := svc.CreateAccount(ctx, AccountCreate{
			Username: username, Password: "correct-horse", Roles: []string{"admin"},
		})
		if err != nil {
			t.Fatal(err)
		}
		uc, err := svc.UserCtx(ctx, acct.User)
		if err != nil {
			t.Fatal(err)
		}
		page, err := svc.Facets(ctx, uc, FacetQuery{Dimension: "album", Order: FacetSortLabel, Limit: 50})
		if err != nil {
			t.Fatalf("enumerating albums: %v", err)
		}
		for _, b := range page.Buckets {
			if b.Label == "Folded" {
				albumPID = b.EntityPID
			}
		}
		if albumPID == "" {
			t.Fatalf("the scanned library has no Folded album; buckets %+v", page.Buckets)
		}
		album, err := svc.Album(ctx, uc, albumPID)
		if err != nil {
			t.Fatalf("reading the album: %v", err)
		}
		if want = album.SortKey; want == "" {
			t.Fatal("the scanned album carries no sort key; this test has nothing to repair")
		}
	}()

	// Phase 2: plant the drift an older fold would have left behind. Raw
	// SQL because the facade has no way to store a key model.SortKey would
	// not generate -- which is the whole point of the repair path.
	db, err := sql.Open("sqlite", "file:"+filepath.Join(dataDir, "waxbin.db"))
	if err != nil {
		t.Fatal(err)
	}
	res, err := db.ExecContext(context.Background(),
		"UPDATE album SET sort_key = 'zzzz stale' WHERE title = ?", "Folded")
	if err != nil {
		t.Fatalf("planting a stale sort key: %v", err)
	}
	if n, err := res.RowsAffected(); err != nil || n != 1 {
		t.Fatalf("planting a stale sort key touched %d rows (err %v), want 1", n, err)
	}
	if err := db.Close(); err != nil {
		t.Fatal(err)
	}

	// Phase 3: reopen with no scan. Only the startup one-shot can heal it.
	ctx, cancel := context.WithCancel(context.Background())
	store, err := wdb.Open(ctx, filepath.Join(dataDir, "waxdeck.db"))
	if err != nil {
		cancel()
		t.Fatal(err)
	}
	group := supervise.NewGroup(log)
	svc, err := Open(ctx, Config{
		DataDir: dataDir,
		Roots:   []Root{{Name: "lib", Path: libDir}},
		Logger:  log,
	}, store, group)
	if err != nil {
		cancel()
		store.Close()
		t.Fatal(err)
	}
	t.Cleanup(func() {
		cancel()
		group.Wait()
		svc.Close()
		store.Close()
	})
	user, err := svc.UserByName(ctx, username)
	if err != nil {
		t.Fatal(err)
	}
	uc, err := svc.UserCtx(ctx, user)
	if err != nil {
		t.Fatal(err)
	}

	// The refresh is a supervised worker, so it lands after Open returns.
	got := "zzzz stale"
	deadline := time.Now().Add(15 * time.Second)
	for time.Now().Before(deadline) {
		album, err := svc.Album(ctx, uc, albumPID)
		if err != nil {
			t.Fatalf("reading the album after reopen: %v", err)
		}
		if got = album.SortKey; got == want {
			return
		}
		time.Sleep(50 * time.Millisecond)
	}
	t.Fatalf("the reopened catalog still reports sort key %q; want the regenerated %q", got, want)
}
