package service

import (
	"context"
	"math"
	"time"

	"github.com/colespringer/waxbin"
)

// The generated-thumbnail cache's admin surface: a census and a prune.
//
// The cache is derived data end to end - every row is a re-encode of a
// stored source image, keyed by that source and the ladder rung it was
// asked for. Nothing here can lose a picture: a pruned entry is
// regenerated by the next request that asks for it, at the cost of one
// decode. That is what makes a prune an operator's tool rather than a
// destructive one, and why there is no scheduled sweep behind it - the
// rung ladder bounds how many derivatives a cover can accumulate going
// forward, so this exists to clean up what a pre-ladder history left.

// ThumbCacheDTO censuses the generated thumbnail cache.
type ThumbCacheDTO struct {
	Rows  int
	Bytes int64
	// Sources is how many source images have at least one derivative,
	// out of ArtSources.
	Sources    int
	ArtSources int
	// ArtSourceBytes is what the originals cost, which is the figure
	// Bytes is read against.
	ArtSourceBytes int64
	// OldestAtNS and NewestAtNS are unix nanoseconds, both zero when the
	// cache is empty.
	OldestAtNS int64
	NewestAtNS int64
	Rungs      []ThumbRungDTO
}

// ThumbRungDTO is one ladder rung's share of the cache.
type ThumbRungDTO struct {
	Size  int
	Rows  int
	Bytes int64
}

// ThumbPruneDTO reports what a prune dropped.
type ThumbPruneDTO struct {
	Removed    int
	FreedBytes int64
}

// ThumbCacheStats censuses the generated thumbnail cache. Administrators
// only: it spans every library.
func (l *Library) ThumbCacheStats(ctx context.Context, uc *UserCtx) (ThumbCacheDTO, error) {
	if !uc.Admin {
		return ThumbCacheDTO{}, &Error{Kind: KindForbidden, Msg: "administrators only"}
	}
	rep, err := l.lib.ThumbCacheStats(ctx)
	if err != nil {
		return ThumbCacheDTO{}, classify(err)
	}
	out := ThumbCacheDTO{
		Rows: rep.Rows, Bytes: rep.Bytes,
		Sources: rep.Sources, ArtSources: rep.ArtSources,
		ArtSourceBytes: rep.ArtSourceBytes,
		OldestAtNS:     rep.OldestAt, NewestAtNS: rep.NewestAt,
	}
	for _, r := range rep.Rungs {
		out.Rungs = append(out.Rungs, ThumbRungDTO{Size: r.Size, Rows: r.Rows, Bytes: r.Bytes})
	}
	return out, nil
}

// maxPruneAgeSeconds is the largest age a prune can carry: the point
// past which seconds no longer fit a time.Duration's nanoseconds.
const maxPruneAgeSeconds = int64(math.MaxInt64 / int64(time.Second))

// PruneThumbnails drops cached thumbnails to fit the policy.
// Administrators only.
//
// Both bounds are pointers the whole way down, because zero is a value
// here and not an absence: an age of zero drops every entry and a
// budget of zero empties the cache, which are meaningful requests. A
// policy with neither bound set is the one that is refused - the
// catalog refuses it too, and answering it as "everything" would turn a
// client that forgot to send its fields into a cache wipe.
func (l *Library) PruneThumbnails(ctx context.Context, uc *UserCtx, olderThanSeconds, maxBytes *int64) (ThumbPruneDTO, error) {
	if !uc.Admin {
		return ThumbPruneDTO{}, &Error{Kind: KindForbidden, Msg: "administrators only"}
	}
	if olderThanSeconds == nil && maxBytes == nil {
		return ThumbPruneDTO{}, errInvalid("a prune needs an age or a byte budget")
	}
	var policy waxbin.ThumbPrunePolicy
	if olderThanSeconds != nil {
		if *olderThanSeconds < 0 {
			return ThumbPruneDTO{}, errInvalid("olderThanSeconds cannot be negative")
		}
		// A Duration is nanoseconds in an int64, so anything past about
		// 292 years wraps - and what it wraps to is a small positive
		// age, which is a cache wipe answering a request that meant
		// "keep everything". Refused rather than clamped: an operator
		// who typed a number this size meant something the field cannot
		// express, and prune is not a verb to guess at.
		if *olderThanSeconds > maxPruneAgeSeconds {
			return ThumbPruneDTO{}, errInvalid("olderThanSeconds is too large")
		}
		age := time.Duration(*olderThanSeconds) * time.Second
		policy.OlderThan = &age
	}
	if maxBytes != nil {
		if *maxBytes < 0 {
			return ThumbPruneDTO{}, errInvalid("maxBytes cannot be negative")
		}
		budget := *maxBytes
		policy.MaxBytes = &budget
	}
	removed, freed, err := l.lib.PruneThumbnails(ctx, policy)
	if err != nil {
		return ThumbPruneDTO{}, classify(err)
	}
	out := ThumbPruneDTO{Removed: removed, FreedBytes: freed}
	// The policy is audited as it was asked for, absences included: a
	// row saying only "maxBytes 0" and one saying "age 0" are different
	// operator decisions with the same result.
	detail := map[string]any{"removed": out.Removed, "freedBytes": out.FreedBytes}
	if olderThanSeconds != nil {
		detail["olderThanSeconds"] = *olderThanSeconds
	}
	if maxBytes != nil {
		detail["maxBytes"] = *maxBytes
	}
	l.Audit(ctx, uc, "thumbnails.prune", AuditTarget{Kind: "thumbnails"}, detail)
	return out, nil
}
