package service

import (
	"context"
	"math"
	"time"

	"github.com/colespringer/waxbin"
)

// The generated-thumbnail cache's admin surface: a census and a prune.
//
// The cache is derived data end to end - every row is a re-encode of a
// stored source image, keyed by that source and the ladder rung it was
// asked for. Nothing here can lose a picture: a pruned entry is
// regenerated by the next request that asks for it, at the cost of one
// decode. That is what makes a prune an operator's tool rather than a
// destructive one, and why there is no scheduled sweep behind it - the
// rung ladder bounds how many derivatives a cover can accumulate going
// forward, so this exists to clean up what a pre-ladder history left.

// ThumbCacheDTO censuses the generated thumbnail cache.
type ThumbCacheDTO struct {
	Rows  int
	Bytes int64
	// Sources is how many source images have at least one derivative,
	// out of ArtSources.
	Sources    int
	ArtSources int
	// ArtSourceBytes is what the originals cost, which is the figure
	// Bytes is read against.
	ArtSourceBytes int64
	// OldestAtNS and NewestAtNS are unix nanoseconds, both zero when the
	// cache is empty.
	OldestAtNS int64
	NewestAtNS int64
	Rungs      []ThumbRungDTO
}

// ThumbRungDTO is one ladder rung's share of the cache.
type ThumbRungDTO struct {
	Size  int
	Rows  int
	Bytes int64
}

// ThumbPruneDTO reports what a prune dropped.
type ThumbPruneDTO struct {
	Removed    int
	FreedBytes int64
}

// ThumbCacheStats censuses the generated thumbnail cache. Administrators
// only: it spans every library.
func (l *Library) ThumbCacheStats(ctx context.Context, uc *UserCtx) (ThumbCacheDTO, error) {
	if !uc.Admin {
		return ThumbCacheDTO{}, &Error{Kind: KindForbidden, Msg: "administrators only"}
	}
	rep, err := l.lib.ThumbCacheStats(ctx)
	if err != nil {
		return ThumbCacheDTO{}, classify(err)
	}
	out := ThumbCacheDTO{
		Rows: rep.Rows, Bytes: rep.Bytes,
		Sources: rep.Sources, ArtSources: rep.ArtSources,
		ArtSourceBytes: rep.ArtSourceBytes,
		OldestAtNS:     rep.OldestAt, NewestAtNS: rep.NewestAt,
	}
	for _, r := range rep.Rungs {
		out.Rungs = append(out.Rungs, ThumbRungDTO{Size: r.Size, Rows: r.Rows, Bytes: r.Bytes})
	}
	return out, nil
}

// maxPruneAgeSeconds is the largest age a prune can carry: the point
// past which seconds no longer fit a time.Duration's nanoseconds.
const maxPruneAgeSeconds = int64(math.MaxInt64 / int64(time.Second))

// PruneThumbnails drops cached thumbnails to fit the policy.
// Administrators only.
func (l *Library) PruneThumbnails(ctx context.Context, uc *UserCtx, olderThanSeconds, maxBytes *int64) (ThumbPruneDTO, error) {
	if !uc.Admin {
		return ThumbPruneDTO{}, &Error{Kind: KindForbidden, Msg: "administrators only"}
	}
	age, budget, err := prunePolicy(olderThanSeconds, maxBytes)
	if err != nil {
		return ThumbPruneDTO{}, err
	}
	removed, freed, err := l.lib.PruneThumbnails(ctx, waxbin.ThumbPrunePolicy{OlderThan: age, MaxBytes: budget})
	if err != nil {
		return ThumbPruneDTO{}, classify(err)
	}
	l.Audit(ctx, uc, "thumbnails.prune", AuditTarget{Kind: "thumbnails"},
		pruneAuditDetail(removed, freed, olderThanSeconds, maxBytes))
	return ThumbPruneDTO{Removed: removed, FreedBytes: freed}, nil
}

// prunePolicy validates a cache prune's bounds. Zero is a value on both
// axes, so absence stays a nil pointer, and a policy with neither is
// refused rather than read as "everything".
func prunePolicy(olderThanSeconds, maxBytes *int64) (*time.Duration, *int64, error) {
	if olderThanSeconds == nil && maxBytes == nil {
		return nil, nil, errInvalid("a prune needs an age or a byte budget")
	}
	var age *time.Duration
	if olderThanSeconds != nil {
		if *olderThanSeconds < 0 {
			return nil, nil, errInvalid("olderThanSeconds cannot be negative")
		}
		// Past this a Duration wraps to a small age, which would wipe a
		// cache the operator meant to keep.
		if *olderThanSeconds > maxPruneAgeSeconds {
			return nil, nil, errInvalid("olderThanSeconds is too large")
		}
		d := time.Duration(*olderThanSeconds) * time.Second
		age = &d
	}
	var budget *int64
	if maxBytes != nil {
		if *maxBytes < 0 {
			return nil, nil, errInvalid("maxBytes cannot be negative")
		}
		b := *maxBytes
		budget = &b
	}
	return age, budget, nil
}

// pruneAuditDetail records a prune's policy as it was asked for, absences
// included: "maxBytes 0" and "age 0" are different decisions.
func pruneAuditDetail(removed int, freed int64, olderThanSeconds, maxBytes *int64) map[string]any {
	detail := map[string]any{"removed": removed, "freedBytes": freed}
	if olderThanSeconds != nil {
		detail["olderThanSeconds"] = *olderThanSeconds
	}
	if maxBytes != nil {
		detail["maxBytes"] = *maxBytes
	}
	return detail
}
